In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas import DataFrame as DF
from sympy import diff
from sympy.abc import x,y
from sympy import cos
from sympy import *
from sympy import lambdify
from itertools import product
import random
from scipy.linalg import norm

**Define path.**

In [14]:
# Defining path to folder raw data is saved in
path = "C:/Users/robtk/OneDrive/Desktop/DIAS Internship/Raw data/Harmonic oscillator warm up/"

### Set display of pandas dataframes and Series to 11 decimal places

In [15]:
pd.set_option("display.precision", 11)

**Read in the outputs for 2 2x2 matrices**

In [16]:
X2_by_2 = pd.read_pickle(path+"X.pkl")
V2_by_2 = pd.read_pickle(path+"V.pkl")

X2 = pd.read_pickle(path+"Xb.pkl")
V2 = pd.read_pickle(path+"Vb.pkl")

**Check that the Gauss' law constraint is conserved.**

In [17]:
X2_by_2

X 1  \
0                  [[-1.2648031177873595, 0.28965090823750295], [...   
0.1                [[-1.266024586128383, 0.3075498233453539], [0....   
0.2                [[-1.2672461453989399, 0.3254499316527957], [0...   
0.3                [[-1.2684206793138693, 0.3427458500505543], [0...   
0.4                [[-1.2695023596759814, 0.3588490235768357], [0...   
...                                                              ...   
9.5                [[-1.2553307128237747, 0.3864624075261496], [0...   
9.6                [[-1.256553976865044, 0.4045837340315353], [0....   
9.700000000000001  [[-1.2576228624582029, 0.4207220073740257], [0...   
9.8                [[-1.2584778821555025, 0.43411357363433767], [...   
9.9                [[-1.2590696112331297, 0.4441241603022393], [0...   

                                                                 X 2  
0                  [[-0.988786234734847, -8.808868141843881], [-9...  
0.1                [[-0.9924837407927861, -8.82448803046022], [-9...  
0.2                [[-0.9961812908590642, -8.840108058987312], [-...  
0.3                [[-0.9998774849649374, -8.855750406355776], [-...  
0.4                [[-1.0035714229022201, -8.871438686484098], [-...  
...                                                              ...  
9.5                [[-1.3513982692174915, -10.418536239755582], [...  
9.6                [[-1.3554268690283275, -10.435619594516812], [...  
9.700000000000001  [[-1.3594517279362057, -10.452779362294871], [...  
9.8                [[-1.3634722119282914, -10.47004855952829], [-...  
9.9                [[-1.3674881329031612, -10.487456115722527], [...  

[100 rows x 2 columns]

In [18]:
# Define the commutator
def commutator(A,B):
    
    # matmul() multiplies two matrices together
    return np.matmul(A,B) - np.matmul(B,A)

In [19]:
i = 0
while i < len(X2.iloc[:,0]):
    
    # Computes the sum of the commutators of Xi and Vi and if they equal zero move on to the next one.
    
    Gauss = commutator(np.array(X2.iloc[i,0]), np.array(V2.iloc[i,0])) + commutator(np.array(X2.iloc[i,1]), np.array(V2.iloc[i,1]))
    i+=1
    print(i)
    # Check if the answer equals the zero matrix.
    if np.all(np.isclose(Gauss, 0)) != True:
        
    # If the sum is printed then the commutator does not equal the zero matrix stop the loop and print what the answer is.
        print(Gauss)
        break
        
    print(Gauss)

1
[[-7.95353117e-10 -2.64321898e-10]
 [ 9.18134901e-10  7.95807864e-10]]
2
[[-8.07631295e-10 -2.59433364e-10]
 [ 9.18589649e-10  8.09905032e-10]]
3
[[-8.01719580e-10 -2.68528311e-10]
 [ 9.16315912e-10  8.02629074e-10]]
4
[[-8.03538569e-10 -2.56022759e-10]
 [ 9.13587428e-10  8.04448064e-10]]
5
[[-7.94898369e-10 -2.57387001e-10]
 [ 9.10858944e-10  7.95353117e-10]]
6
[[-7.94898369e-10 -2.73303158e-10]
 [ 9.20408638e-10  7.94898369e-10]]
7
[[-7.93079380e-10 -2.80806489e-10]
 [ 9.20863386e-10  7.92169885e-10]]
8
[[-8.03083822e-10 -2.77395884e-10]
 [ 9.30413080e-10  8.02174327e-10]]
9
[[-7.97626853e-10 -2.78760126e-10]
 [ 9.27684596e-10  7.96717359e-10]]
10
[[-7.99445843e-10 -2.76031642e-10]
 [ 9.36779543e-10  7.99445843e-10]]


**From the above code it is clear that Gauss' law is conserved throughout the simulation.**

**Now check if the Hamiltonian is conserved.**


In [20]:
# Define the Lagrangian

def L(X_list, V_list, g):
    
    X_array = np.array(X_list)
    V_array = np.array(X_list)
    term_1 =  np.sum( np.trace( (V_array)**2 ) )
    
    # Calculate the sum of commutators found in the second term of the lagrangian
    for el in X_list:
        X_cut = [x for x in X_list if x != el]
        Sum2 = np.sum( np.trace( (commutator(el,X_cut))**2 ) ) 
    
    term_2 = 1/2 * Sum2
    
    return 1/(2*g**2) * (term_1 + term_2)

# Define the Hamiltonian

def H(X_list, V_list, g):
    
    
    X_array = np.array(X_list)
    V_array = np.array(X_list)
    term_1 =  np.sum( np.trace( (V_array)**2 ) )
    
    # Calculate the sum of commutators found in the second term of the lagrangian
    for el in X_list:
        X_cut = [x for x in X_list if x != el]
        Sum2 = np.sum( np.trace( (commutator(el,X_cut))**2 ) ) 
    
    term_2 = 1/2 * Sum2
    
    return 1/(2*g**2) * (term_1 - term_2)
    

In [21]:
V2_by_2

V 1  \
0                  [[-0.12056495110501841, 1.7695576970987381], [...   
0.1                [[-0.12293121509432986, 1.7999734588103529], [...   
0.2                [[-0.12057689632601384, 1.7697211753819215], [...   
0.3                [[-0.11354807401713776, 1.679422038844256], [-...   
0.4                [[-0.102055953882069, 1.531815551414121], [-1....   
...                                                              ...   
9.5                [[-0.12785800805497968, 1.8831984301539302], [...   
9.6                [[-0.11565780787416945, 1.7264656199285744], [...   
9.700000000000001  [[-0.09710299873130834, 1.488142630955383], [-...   
9.8                [[-0.07305645688529439, 1.1793335003816856], [...   
9.9                [[-0.04466009360102731, 0.8147105614815209], [...   

                                                                 V 2  
0                  [[-0.3696892043800882, -1.5626698061744178], [...  
0.1                [[-0.3697800075050011, -1.5616465939032302], [...  
0.2                [[-0.3697061623936174, -1.5627376246795663], [...  
0.3                [[-0.3695174205987425, -1.5661352206002537], [...  
0.4                [[-0.36926287514974304, -1.571929358455459], [...  
...                                                              ...  
9.5                [[-0.403010805542756, -1.7056717217486954], [-...  
9.6                [[-0.40268803522367874, -1.7115904531502943], ...  
9.700000000000001  [[-0.4022732656525274, -1.720928724049069], [-...  
9.8                [[-0.4018206947481504, -1.7334066826741967], [...  
9.9                [[-0.40136467677955767, -1.7484886781514128], ...  

[100 rows x 2 columns]

In [24]:
i = 0
while i < len(X2_by_2["X 1"].values):
    
    # Create a list of the two coordinate matrices for the position.
    X_list = [X2_by_2["X 1"].values[i], X2_by_2["X 2"].values[i]]
    V_list = [V2_by_2["V 1"].values[i], V2_by_2["V 2"].values[i]]

    
    print(H(X_list, V_list, 1))
    i += 1

49.51503713461014
49.730181076815846
49.88987846584362
49.99693947378928
50.06157621811119
50.100047113077586
50.132426491450744
50.179795703795484
50.261241716288936
50.3910866505576
50.57674978095848
50.81756349902111
51.10473623809864
51.42249511598234
51.75027104070749
52.06563346229256
52.34756401876434
52.579596741966085
52.75235852200757
52.8651188747444
52.92609405447675
52.951428982387384
52.962975908221416
52.985172233364
53.04146336049786
53.150796844015076
53.32471738488129
53.56551545696444
53.86573465959913
54.20914435050062
54.5730632119696
54.93170912389834
55.260083779853446
55.53780434105645
55.75228672241763
55.90077035764955
55.99084244308236
56.039346973784966
56.06981617265582
56.108799700161306
56.18165182880496
56.308437365975365
56.500614847700405
56.759047624728225
57.07369392582906
57.42506491627339
57.787255326412456
58.132089702987805
58.433732171482575
58.67301324121142
58.84075295531104
58.939505734438825
58.98339853719022
58.996042656003205
59.0068207401

**From derivation in page**

# Check conservation of angular momentum

**Angular momentum is $Tr(Xi\dot Xj - Xj\dot Xi)$**

In [13]:
def angular_momentum(X2_by_2, V2_by_2):
    
    i = 0
    while i < len(X2_by_2):
        
        Xi = X2_by_2[i]
        Vi = V2_by_2[i]
        np.sum(np.trace( np.matmul(Xi, V2_by_2) - np.matmul(X2_by_2, Vi) ))
        
        i += 1

In [14]:
angular_momentum(X2_by_2, V2_by_2)

KeyError: 0

# Lyapunov exponent

**Using the l_2 for the separation.**

In [9]:
A_list3 = pd.read_csv(path + "A_vector_initial.txt", sep = ";",
                        names = ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9"],
                      index_col=False)
A_list3

A1  \
0   (0.000000000000000,0.000000000000000) (0.00000...   
1   (0.000000000000000,0.000000000000000) (0.00000...   
2   (0.000000000000000,0.000000000000000) (0.00000...   
3   (0.000000000000000,0.000000000000000) (0.00000...   
4   (0.000000000000000,0.000000000000000) (0.00000...   
5   (0.000000000000000,0.000000000000000) (0.00000...   
6   (0.000000000000000,0.000000000000000) (0.00000...   
7   (0.000000000000000,0.000000000000000) (0.00000...   
8   (0.000000000000000,0.000000000000000) (0.00000...   
9   (0.000000000000000,0.000000000000000) (0.00000...   
10  (0.000000000000000,0.000000000000000) (0.00000...   
11  (0.000000000000000,0.000000000000000) (0.00000...   
12  (0.000000000000000,0.000000000000000) (0.00000...   
13  (0.000000000000000,0.000000000000000) (0.00000...   
14  (0.000000000000000,0.000000000000000) (0.00000...   
15  (0.000000000000000,0.000000000000000) (0.00000...   
16  (0.000000000000000,0.000000000000000) (0.00000...   
17  (0.000000000000000,0.000000000000000) (0.00000...   
18  (0.000000000000000,0.000000000000000) (0.00000...   

                                                   A2  A3  A4  A5  A6  A7  A8  \
0                                                 NaN NaN NaN NaN NaN NaN NaN   
1                                                 NaN NaN NaN NaN NaN NaN NaN   
2   (0.000000000000000,0.000000000000000) (0.00000... NaN NaN NaN NaN NaN NaN   
3                                                 NaN NaN NaN NaN NaN NaN NaN   
4   (0.000000000000000,0.000000000000000) (0.00000... NaN NaN NaN NaN NaN NaN   
5                                                 NaN NaN NaN NaN NaN NaN NaN   
6   (0.000000000000000,0.000000000000000) (0.00000... NaN NaN NaN NaN NaN NaN   
7                                                 NaN NaN NaN NaN NaN NaN NaN   
8   (0.000000000000000,0.000000000000000) (0.00000... NaN NaN NaN NaN NaN NaN   
9                                                 NaN NaN NaN NaN NaN NaN NaN   
10  (0.000000000000000,0.000000000000000) (0.00000... NaN NaN NaN NaN NaN NaN   
11                                                NaN NaN NaN NaN NaN NaN NaN   
12  (0.000000000000000,0.000000000000000) (0.00000... NaN NaN NaN NaN NaN NaN   
13                                                NaN NaN NaN NaN NaN NaN NaN   
14  (0.000000000000000,0.000000000000000) (0.00000... NaN NaN NaN NaN NaN NaN   
15                                                NaN NaN NaN NaN NaN NaN NaN   
16  (0.000000000000000,0.000000000000000) (0.00000... NaN NaN NaN NaN NaN NaN   
17                                                NaN NaN NaN NaN NaN NaN NaN   
18                                                NaN NaN NaN NaN NaN NaN NaN   

    A9  
0  NaN  
1  NaN  
2  NaN  
3  NaN  
4  NaN  
5  NaN  
6  NaN  
7  NaN  
8  NaN  
9  NaN  
10 NaN  
11 NaN  
12 NaN  
13 NaN  
14 NaN  
15 NaN  
16 NaN  
17 NaN  
18 NaN

In [30]:
X_list3 = pd.read_csv(path + "X_vector_initial.txt", sep = "\s+;,",
                      names = ["X1", "X2", "X3", "X4", "X5", "X6", "X7", "X8", "X9"],
                      index_col=False)
X_list3["X1"][0]

<ipython-input-30-9f5b6aa4e332>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  X_list3 = pd.read_csv(path + "X_vector_initial.txt", sep = "\s+;,",


'0.414088665335914,0.225567949423011,0.413464231323263,-2.539330153266858,-0.218056106847159,0.545812377560037,;0.413464231323263,2.539330153266858,1.469293298084035,0.145926865506495,-0.432501293641333,-0.077222086347351,;-0.218056106847159,-0.545812377560037,-0.432501293641333,0.077222086347351,-1.883381963419949,-0.371494814929506,;'