In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas import DataFrame as DF
from sympy import diff
from sympy.abc import x,y
from sympy import cos
from sympy import *
from sympy import lambdify
from itertools import product
import random
from scipy.linalg import norm

**Define path.**

In [92]:
# Defining path to folder raw data is saved in
path = "C:/Users/robtk/OneDrive/Desktop/DIAS Internship/Raw data/Harmonic oscillator warm up/"

### Set display of pandas dataframes and Series to 11 decimal places

In [93]:
pd.set_option("display.precision", 11)

**Read in the outputs for 2 2x2 matrices**

In [94]:
X2_by_2 = pd.read_pickle(path+"X.pkl")
V2_by_2 = pd.read_pickle(path+"V.pkl")

X2 = pd.read_pickle(path+"Xb.pkl")
V2 = pd.read_pickle(path+"Vb.pkl")

X_test = pd.read_pickle(path+"X_test.pkl")
V_test = pd.read_pickle(path+"V_test.pkl")

X_test = pd.read_pickle(path+"X_test9.pkl")
V_test = pd.read_pickle(path+"V_test9.pkl")


**Check that the Gauss' law constraint is conserved.**

In [95]:
X2_by_2

X 1  \
0                  [[-1.2648031177873595, 0.28965090823750295], [...   
0.1                [[-1.266024586128383, 0.3075498233453539], [0....   
0.2                [[-1.2672461453989399, 0.3254499316527957], [0...   
0.3                [[-1.2684206793138693, 0.3427458500505543], [0...   
0.4                [[-1.2695023596759814, 0.3588490235768357], [0...   
...                                                              ...   
9.5                [[-1.2553307128237747, 0.3864624075261496], [0...   
9.6                [[-1.256553976865044, 0.4045837340315353], [0....   
9.700000000000001  [[-1.2576228624582029, 0.4207220073740257], [0...   
9.8                [[-1.2584778821555025, 0.43411357363433767], [...   
9.9                [[-1.2590696112331297, 0.4441241603022393], [0...   

                                                                 X 2  
0                  [[-0.988786234734847, -8.808868141843881], [-9...  
0.1                [[-0.9924837407927861, -8.82448803046022], [-9...  
0.2                [[-0.9961812908590642, -8.840108058987312], [-...  
0.3                [[-0.9998774849649374, -8.855750406355776], [-...  
0.4                [[-1.0035714229022201, -8.871438686484098], [-...  
...                                                              ...  
9.5                [[-1.3513982692174915, -10.418536239755582], [...  
9.6                [[-1.3554268690283275, -10.435619594516812], [...  
9.700000000000001  [[-1.3594517279362057, -10.452779362294871], [...  
9.8                [[-1.3634722119282914, -10.47004855952829], [-...  
9.9                [[-1.3674881329031612, -10.487456115722527], [...  

[100 rows x 2 columns]

In [96]:
# Define the commutator
def commutator(A,B):
    
    # matmul() multiplies two matrices together
    return np.matmul(A,B) - np.matmul(B,A)

In [97]:
i = 0
while i < len(X_test.iloc[:,0]):
    
    # Computes the sum of the commutators of Xi and Vi and if they equal zero move on to the next one.
    
    Gauss = commutator(np.array(X_test.iloc[i,0]), np.array(V_test.iloc[i,0])) + commutator(np.array(X_test.iloc[i,1]), np.array(V_test.iloc[i,1]))
    i+=1
    print(i)
    # Check if the answer equals the zero matrix.
    if np.all(np.isclose(Gauss, 0)) != True:
        
    # If the sum is printed then the commutator does not equal the zero matrix stop the loop and print what the answer is.
        print(Gauss)
        
    print(Gauss)

1
[[0. 0.]
 [0. 0.]]
2
[[-0.29128385  0.12487493]
 [ 0.84563491  0.29128385]]
[[-0.29128385  0.12487493]
 [ 0.84563491  0.29128385]]
3
[[-0.5783839   0.24611287]
 [ 1.68655162  0.5783839 ]]
[[-0.5783839   0.24611287]
 [ 1.68655162  0.5783839 ]]
4
[[-0.85725826  0.36017678]
 [ 2.51814083  0.85725826]]
[[-0.85725826  0.36017678]
 [ 2.51814083  0.85725826]]
5
[[-1.12414304  0.46372677]
 [ 3.3360064   1.12414304]]
[[-1.12414304  0.46372677]
 [ 3.3360064   1.12414304]]
6
[[-1.37567738  0.55371144]
 [ 4.13606026  1.37567738]]
[[-1.37567738  0.55371144]
 [ 4.13606026  1.37567738]]
7
[[-1.60901184  0.62745094]
 [ 4.91460406  1.60901184]]
[[-1.60901184  0.62745094]
 [ 4.91460406  1.60901184]]
8
[[-1.82189579  0.68270877]
 [ 5.6683937   1.82189579]]
[[-1.82189579  0.68270877]
 [ 5.6683937   1.82189579]]
9
[[-2.01273971  0.71775   ]
 [ 6.39468383  2.01273971]]
[[-2.01273971  0.71775   ]
 [ 6.39468383  2.01273971]]
10
[[-2.18064959  0.7313837 ]
 [ 7.09125044  2.18064959]]
[[-2.18064959  0.7313837 

136
[[-31.36202967 -17.67259839]
 [ 39.4016093   31.36202967]]
[[-31.36202967 -17.67259839]
 [ 39.4016093   31.36202967]]
137
[[-32.65087877 -17.61470155]
 [ 36.12302096  32.65087877]]
[[-32.65087877 -17.61470155]
 [ 36.12302096  32.65087877]]
138
[[-34.01598849 -17.28388579]
 [ 32.5157448   34.01598849]]
[[-34.01598849 -17.28388579]
 [ 32.5157448   34.01598849]]
139
[[-35.42333054 -16.65320219]
 [ 28.56191154  35.42333054]]
[[-35.42333054 -16.65320219]
 [ 28.56191154  35.42333054]]
140
[[-36.83085601 -15.69436485]
 [ 24.24534714  36.83085601]]
[[-36.83085601 -15.69436485]
 [ 24.24534714  36.83085601]]
141
[[-38.19044219 -14.37900302]
 [ 19.55507488  38.19044219]]
[[-38.19044219 -14.37900302]
 [ 19.55507488  38.19044219]]
142
[[-39.45088062 -12.68048659]
 [ 14.48959516  39.45088062]]
[[-39.45088062 -12.68048659]
 [ 14.48959516  39.45088062]]
143
[[-40.56170131 -10.57635647]
 [  9.06164563  40.56170131]]
[[-40.56170131 -10.57635647]
 [  9.06164563  40.56170131]]
144
[[-41.47739819  -8.0

[[-23.94668567 -70.68425171]
 [284.46602384  23.94668567]]
237
[[ -32.568795   -111.56390064]
 [ 305.51645845   32.568795  ]]
[[ -32.568795   -111.56390064]
 [ 305.51645845   32.568795  ]]
238
[[ -42.15498863 -143.89603366]
 [ 304.71323039   42.15498863]]
[[ -42.15498863 -143.89603366]
 [ 304.71323039   42.15498863]]
239
[[ -52.00720111 -164.63834288]
 [ 281.02288174   52.00720111]]
[[ -52.00720111 -164.63834288]
 [ 281.02288174   52.00720111]]
240
[[ -61.35140124 -171.47221341]
 [ 235.17468883   61.35140124]]
[[ -61.35140124 -171.47221341]
 [ 235.17468883   61.35140124]]
241
[[ -69.36526215 -163.00083666]
 [ 169.72398008   69.36526215]]
[[ -69.36526215 -163.00083666]
 [ 169.72398008   69.36526215]]
242
[[ -75.23226889 -138.96597784]
 [  89.0669414    75.23226889]]
[[ -75.23226889 -138.96597784]
 [  89.0669414    75.23226889]]
243
[[ -78.23912527 -100.46554645]
 [  -0.64304887   78.23912527]]
[[ -78.23912527 -100.46554645]
 [  -0.64304887   78.23912527]]
244
[[-77.89825276 -50.09352814

 [-620.68035425  -27.42754919]]
[[  27.42754919  596.31943152]
 [-620.68035425  -27.42754919]]
334
[[  66.36992962  458.41958619]
 [-117.14353958  -66.36992962]]
[[  66.36992962  458.41958619]
 [-117.14353958  -66.36992962]]
335
[[ 65.53645071 149.2866786 ]
 [453.86687626 -65.53645071]]
[[ 65.53645071 149.2866786 ]
 [453.86687626 -65.53645071]]
336
[[  23.58781705 -220.17302823]
 [ 877.08297103  -23.58781705]]
[[  23.58781705 -220.17302823]
 [ 877.08297103  -23.58781705]]
337
[[ -44.9137784  -509.35600456]
 [ 982.73468756   44.9137784 ]]
[[ -44.9137784  -509.35600456]
 [ 982.73468756   44.9137784 ]]
338
[[-114.27136406 -601.98583262]
 [ 716.8415319   114.27136406]]
[[-114.27136406 -601.98583262]
 [ 716.8415319   114.27136406]]
339
[[-157.05113883 -453.37319714]
 [ 169.61633652  157.05113883]]
[[-157.05113883 -453.37319714]
 [ 169.61633652  157.05113883]]
340
[[-154.88415154 -113.08157868]
 [-450.73686738  154.88415154]]
[[-154.88415154 -113.08157868]
 [-450.73686738  154.88415154]]
341

 [-1664.72530319   243.57268097]]
429
[[   27.26981563  1370.23471597]
 [-2060.55118211   -27.26981563]]
[[   27.26981563  1370.23471597]
 [-2060.55118211   -27.26981563]]
430
[[ 225.42185271 1013.57135359]
 [-142.75038137 -225.42185271]]
[[ 225.42185271 1013.57135359]
 [-142.75038137 -225.42185271]]
431
[[ 126.03359521 -473.85932512]
 [2000.86887086 -126.03359521]]
[[ 126.03359521 -473.85932512]
 [2000.86887086 -126.03359521]]
432
[[ -166.73399855 -1436.81831631]
 [ 1944.16647696   166.73399855]]
[[ -166.73399855 -1436.81831631]
 [ 1944.16647696   166.73399855]]
433
[[-323.12976369 -757.20538591]
 [-311.316582    323.12976369]]
[[-323.12976369 -757.20538591]
 [-311.316582    323.12976369]]
434
[[ -158.3029596    826.59969977]
 [-2220.74691391   158.3029596 ]]
[[ -158.3029596    826.59969977]
 [-2220.74691391   158.3029596 ]]
435
[[  144.48761086  1491.3602368 ]
 [-1544.93673623  -144.48761086]]
[[  144.48761086  1491.3602368 ]
 [-1544.93673623  -144.48761086]]
436
[[ 232.39100678  427

521
[[ -310.8391228  -2765.68951701]
 [ 3510.603106     310.8391228 ]]
[[ -310.8391228  -2765.68951701]
 [ 3510.603106     310.8391228 ]]
522
[[ -455.31777068   343.46286746]
 [-3197.46266294   455.31777068]]
[[ -455.31777068   343.46286746]
 [-3197.46266294   455.31777068]]
523
[[  361.83016176  2719.1484939 ]
 [-2457.71047314  -361.83016176]]
[[  361.83016176  2719.1484939 ]
 [-2457.71047314  -361.83016176]]
524
[[  237.22561226 -1237.160961  ]
 [ 4127.65861075  -237.22561226]]
[[  237.22561226 -1237.160961  ]
 [ 4127.65861075  -237.22561226]]
525
[[ -551.53243456 -2281.21574528]
 [ 1085.70341965   551.53243456]]
[[ -551.53243456 -2281.21574528]
 [ 1085.70341965   551.53243456]]
526
[[ -138.66785949  2125.39138456]
 [-4516.03808248   138.66785949]]
[[ -138.66785949  2125.39138456]
 [-4516.03808248   138.66785949]]
527
[[ 508.37368399 1524.17756521]
 [ 696.05042636 -508.37368399]]
[[ 508.37368399 1524.17756521]
 [ 696.05042636 -508.37368399]]
528
[[ -165.96275653 -2725.08615407]
 [ 43

613
[[ 871.24806942 2122.0501745 ]
 [1876.91189935 -871.24806942]]
[[ 871.24806942 2122.0501745 ]
 [1876.91189935 -871.24806942]]
614
[[ -842.41689841 -4310.4769865 ]
 [ 3028.64968284   842.41689841]]
[[ -842.41689841 -4310.4769865 ]
 [ 3028.64968284   842.41689841]]
615
[[  323.86608168  4830.5097837 ]
 [-6632.18827062  -323.86608168]]
[[  323.86608168  4830.5097837 ]
 [-6632.18827062  -323.86608168]]
616
[[  164.05752676 -3432.06815769]
 [ 7756.07160686  -164.05752676]]
[[  164.05752676 -3432.06815769]
 [ 7756.07160686  -164.05752676]]
617
[[ -744.97100231   794.77819836]
 [-5869.70229743   744.97100231]]
[[ -744.97100231   794.77819836]
 [-5869.70229743   744.97100231]]
618
[[ 896.50237798 2176.68972314]
 [1934.7962315  -896.50237798]]
[[ 896.50237798 2176.68972314]
 [1934.7962315  -896.50237798]]
619
[[ -886.04630118 -4319.3085873 ]
 [ 2769.23480824   886.04630118]]
[[ -886.04630118 -4319.3085873 ]
 [ 2769.23480824   886.04630118]]
620
[[  413.69456217  5018.52537325]
 [-6414.53630

724
[[-1443.86964235  -480.71219579]
 [-7911.84007429  1443.86964235]]
[[-1443.86964235  -480.71219579]
 [-7911.84007429  1443.86964235]]
725
[[  850.600737   -3391.47218811]
 [12022.08475662  -850.600737  ]]
[[  850.600737   -3391.47218811]
 [12022.08475662  -850.600737  ]]
726
[[  -210.04194557   6662.86433939]
 [-13423.0185903     210.04194557]]
[[  -210.04194557   6662.86433939]
 [-13423.0185903     210.04194557]]
727
[[ -664.40895843 -8394.36889711]
 [11765.65489494   664.40895843]]
[[ -664.40895843 -8394.36889711]
 [11765.65489494   664.40895843]]
728
[[ 1235.73920699  8140.56572651]
 [-7034.51195688 -1235.73920699]]
[[ 1235.73920699  8140.56572651]
 [-7034.51195688 -1235.73920699]]
729
[[-1666.31044214 -5713.74052093]
 [  434.25029805  1666.31044214]]
[[-1666.31044214 -5713.74052093]
 [  434.25029805  1666.31044214]]
730
[[ 1495.27831612  1721.49394775]
 [ 6569.80480035 -1495.27831612]]
[[ 1495.27831612  1721.49394775]
 [ 6569.80480035 -1495.27831612]]
731
[[ -1059.98903695   29

786
[[ -1012.02458166   5540.40421305]
 [-16402.39732467   1012.02458166]]
[[ -1012.02458166   5540.40421305]
 [-16402.39732467   1012.02458166]]
787
[[ -1427.33377472 -10980.99333279]
 [ 11761.99523289   1427.33377472]]
[[ -1427.33377472 -10980.99333279]
 [ 11761.99523289   1427.33377472]]
788
[[ 1958.26285921  2510.43000526]
 [ 8027.26867697 -1958.26285921]]
[[ 1958.26285921  2510.43000526]
 [ 8027.26867697 -1958.26285921]]
789
[[   -68.72041288   9370.04574323]
 [-17574.59562648     68.72041288]]
[[   -68.72041288   9370.04574323]
 [-17574.59562648     68.72041288]]
790
[[-2052.32604839 -8977.12347761]
 [ 4075.25571845  2052.32604839]]
[[-2052.32604839 -8977.12347761]
 [ 4075.25571845  2052.32604839]]
791
[[ 1324.25562616 -3460.26521747]
 [15145.56945973 -1324.25562616]]
[[ 1324.25562616 -3460.26521747]
 [15145.56945973 -1324.25562616]]
792
[[  1110.55355013  11355.17905811]
 [-13817.05173313  -1110.55355013]]
[[  1110.55355013  11355.17905811]
 [-13817.05173313  -1110.55355013]]
79

854
[[ 2323.85016405   362.89447591]
 [14341.46730092 -2323.85016405]]
[[ 2323.85016405   362.89447591]
 [14341.46730092 -2323.85016405]]
855
[[ 2338.80417725 13091.36383675]
 [-9285.77990362 -2338.80417725]]
[[ 2338.80417725 13091.36383675]
 [-9285.77990362 -2338.80417725]]
856
[[  -170.75441063  11966.03505539]
 [-23057.84055574    170.75441063]]
[[  -170.75441063  11966.03505539]
 [-23057.84055574    170.75441063]]
857
[[ -2548.78358043  -1546.88977092]
 [-12911.63684517   2548.78358043]]
[[ -2548.78358043  -1546.88977092]
 [-12911.63684517   2548.78358043]]
858
[[ -2388.70872447 -13480.18241222]
 [ 10340.45902681   2388.70872447]]
[[ -2388.70872447 -13480.18241222]
 [ 10340.45902681   2388.70872447]]
859
[[    92.97451523 -12055.92987334]
 [ 23379.15125934    -92.97451523]]
[[    92.97451523 -12055.92987334]
 [ 23379.15125934    -92.97451523]]
860
[[ 2442.11384189  1034.90777242]
 [13836.89989478 -2442.11384189]]
[[ 2442.11384189  1034.90777242]
 [13836.89989478 -2442.11384189]]
86

[[ -1605.32449322 -18403.21783328]
 [ 24469.24118333   1605.32449322]]
[[ -1605.32449322 -18403.21783328]
 [ 24469.24118333   1605.32449322]]
921
[[ -1038.40235713 -17832.31557453]
 [ 26990.22157572   1038.40235713]]
[[ -1038.40235713 -17832.31557453]
 [ 26990.22157572   1038.40235713]]
922
[[  -488.42610882 -16836.78712193]
 [ 28612.67594992    488.42610882]]
[[  -488.42610882 -16836.78712193]
 [ 28612.67594992    488.42610882]]
923
[[ 2.51733834e+01 -1.55588823e+04]
 [ 2.94788405e+04 -2.51733834e+01]]
[[ 2.51733834e+01 -1.55588823e+04]
 [ 2.94788405e+04 -2.51733834e+01]]
924
[[   489.77909232 -14125.98264355]
 [ 29746.32970528   -489.77909232]]
[[   489.77909232 -14125.98264355]
 [ 29746.32970528   -489.77909232]]
925
[[   898.45384254 -12646.51200196]
 [ 29573.3432082    -898.45384254]]
[[   898.45384254 -12646.51200196]
 [ 29573.3432082    -898.45384254]]
926
[[  1248.65095877 -11208.80869517]
 [ 29108.41155052  -1248.65095877]]
[[  1248.65095877 -11208.80869517]
 [ 29108.41155052 

 [ 23790.82746389   3141.27111967]]
[[ -3141.27111967 -23250.71026408]
 [ 23790.82746389   3141.27111967]]
993
[[ -4549.60789768 -10832.25956769]
 [ -8258.89207358   4549.60789768]]
[[ -4549.60789768 -10832.25956769]
 [ -8258.89207358   4549.60789768]]
994
[[ -2414.33946899  10410.05677521]
 [-34345.32576189   2414.33946899]]
[[ -2414.33946899  10410.05677521]
 [-34345.32576189   2414.33946899]]
995
[[  1698.10747089  23544.19296039]
 [-32817.91156573  -1698.10747089]]
[[  1698.10747089  23544.19296039]
 [-32817.91156573  -1698.10747089]]
996
[[ 4416.90228191 17082.90741337]
 [-3583.70304701 -4416.90228191]]
[[ 4416.90228191 17082.90741337]
 [-3583.70304701 -4416.90228191]]
997
[[ 3309.75692539 -4317.36228452]
 [29298.49226737 -3309.75692539]]
[[ 3309.75692539 -4317.36228452]
 [29298.49226737 -3309.75692539]]
998
[[  -815.94523542 -22210.97632818]
 [ 36557.4084624     815.94523542]]
[[  -815.94523542 -22210.97632818]
 [ 36557.4084624     815.94523542]]
999
[[ -4299.25466682 -19936.6754

 [-31693.26805606  -4697.23587851]]
1112
[[ -3575.90609293 -34217.94495559]
 [ 41481.86472347   3575.90609293]]
[[ -3575.90609293 -34217.94495559]
 [ 41481.86472347   3575.90609293]]
1113
[[  2174.78644165  33484.23341902]
 [-48328.63493696  -2174.78644165]]
[[  2174.78644165  33484.23341902]
 [-48328.63493696  -2174.78644165]]
1114
[[  -940.26392281 -31239.55777938]
 [ 52597.71195518    940.26392281]]
[[  -940.26392281 -31239.55777938]
 [ 52597.71195518    940.26392281]]
1115
[[  -396.35482061  28039.69020135]
 [-54440.47756498    396.35482061]]
[[  -396.35482061  28039.69020135]
 [-54440.47756498    396.35482061]]
1116
[[  1440.95863791 -24190.11644567]
 [ 54517.57699947  -1440.95863791]]
[[  1440.95863791 -24190.11644567]
 [ 54517.57699947  -1440.95863791]]
1117
[[ -2510.78812664  20154.50685598]
 [-53115.72991867   2510.78812664]]
[[ -2510.78812664  20154.50685598]
 [-53115.72991867   2510.78812664]]
1118
[[  3252.34376677 -16107.83042961]
 [ 50909.15408288  -3252.34376677]]
[[  32

[[  2931.69383346  41246.0857494 ]
 [-58007.89596161  -2931.69383346]]
[[  2931.69383346  41246.0857494 ]
 [-58007.89596161  -2931.69383346]]
1186
[[ -8044.33419757 -25271.40163817]
 [ -3447.94472728   8044.33419757]]
[[ -8044.33419757 -25271.40163817]
 [ -3447.94472728   8044.33419757]]
1187
[[  3886.52210285 -19865.02632735]
 [ 61921.6436306   -3886.52210285]]
[[  3886.52210285 -19865.02632735]
 [ 61921.6436306   -3886.52210285]]
1188
[[  4796.63974449  42222.94482485]
 [-48035.37335443  -4796.63974449]]
[[  4796.63974449  42222.94482485]
 [-48035.37335443  -4796.63974449]]
1189
[[ -7889.16037207 -13523.28209845]
 [-24361.44547149   7889.16037207]]
[[ -7889.16037207 -13523.28209845]
 [-24361.44547149   7889.16037207]]
1190
[[  1036.0784687  -32433.73623304]
 [ 67320.79510807  -1036.0784687 ]]
[[  1036.0784687  -32433.73623304]
 [ 67320.79510807  -1036.0784687 ]]
1191
[[  7119.7477526   37303.96636214]
 [-24177.67836674  -7119.7477526 ]]
[[  7119.7477526   37303.96636214]
 [-24177.678

[[  4799.20872939 -25731.28170778]
 [ 78625.9082926   -4799.20872939]]
1278
[[  6513.54246456 -15854.02482987]
 [ 71058.52215768  -6513.54246456]]
[[  6513.54246456 -15854.02482987]
 [ 71058.52215768  -6513.54246456]]
1279
[[ 7835.34045238 -6375.6775785 ]
 [61752.35758418 -7835.34045238]]
[[ 7835.34045238 -6375.6775785 ]
 [61752.35758418 -7835.34045238]]
1280
[[ 8798.391099    2253.95028758]
 [51759.37922925 -8798.391099  ]]
[[ 8798.391099    2253.95028758]
 [51759.37922925 -8798.391099  ]]
1281
[[ 9458.0303984   9776.25921549]
 [41911.45408449 -9458.0303984 ]]
[[ 9458.0303984   9776.25921549]
 [41911.45408449 -9458.0303984 ]]
1282
[[ 9878.72757384 16080.56895992]
 [32822.52911392 -9878.72757384]]
[[ 9878.72757384 16080.56895992]
 [32822.52911392 -9878.72757384]]
1283
[[ 10124.93600256  21158.36160575]
 [ 24916.05305534 -10124.93600256]]
[[ 10124.93600256  21158.36160575]
 [ 24916.05305534 -10124.93600256]]
1284
[[ 10254.9579429   25061.333677  ]
 [ 18464.35722414 -10254.9579429 ]]
[[ 

1345
[[ -9844.13454175   2732.84909136]
 [-67020.04207257   9844.13454175]]
[[ -9844.13454175   2732.84909136]
 [-67020.04207257   9844.13454175]]
1346
[[  3307.61084606  60461.27813007]
 [-91441.73505579  -3307.61084606]]
[[  3307.61084606  60461.27813007]
 [-91441.73505579  -3307.61084606]]
1347
[[ 11995.58461132  35502.87416516]
 [ 10011.59926069 -11995.58461132]]
[[ 11995.58461132  35502.87416516]
 [ 10011.59926069 -11995.58461132]]
1348
[[  3678.29673233 -40167.24616279]
 [ 98441.8134458   -3678.29673233]]
[[  3678.29673233 -40167.24616279]
 [ 98441.8134458   -3678.29673233]]
1349
[[-10173.09456261 -57898.37636012]
 [ 43897.04426762  10173.09456261]]
[[-10173.09456261 -57898.37636012]
 [ 43897.04426762  10173.09456261]]
1350
[[ -8927.0835908   11322.37028144]
 [-77229.15522401   8927.0835908 ]]
[[ -8927.0835908   11322.37028144]
 [-77229.15522401   8927.0835908 ]]
1351
[[  6074.41277235  63736.99169939]
 [-80050.6143156   -6074.41277235]]
[[  6074.41277235  63736.99169939]
 [-8005

[[ -9516.89693952  18624.74537942]
 [-94568.16158774   9516.89693952]]
[[ -9516.89693952  18624.74537942]
 [-94568.16158774   9516.89693952]]
1413
[[ 12724.02574299  10612.61400793]
 [ 61005.45156086 -12724.02574299]]
[[ 12724.02574299  10612.61400793]
 [ 61005.45156086 -12724.02574299]]
1414
[[-14075.66389771 -36782.34182797]
 [-20134.59361877  14075.66389771]]
[[-14075.66389771 -36782.34182797]
 [-20134.59361877  14075.66389771]]
1415
[[ 13375.82450544  56844.25970269]
 [-21033.92027784 -13375.82450544]]
[[ 13375.82450544  56844.25970269]
 [-21033.92027784 -13375.82450544]]
1416
[[-11364.48901335 -69251.82569917]
 [ 57522.42210834  11364.48901335]]
[[-11364.48901335 -69251.82569917]
 [ 57522.42210834  11364.48901335]]
1417
[[  8198.93483365  74116.3572678 ]
 [-85959.91820307  -8198.93483365]]
[[  8198.93483365  74116.3572678 ]
 [-85959.91820307  -8198.93483365]]
1418
[[ -4719.0895136  -72329.53009115]
 [105280.78856025   4719.0895136 ]]
[[ -4719.0895136  -72329.53009115]
 [105280.788

1481
[[-15744.98150019 -63187.59545228]
 [ 18520.37872802  15744.98150019]]
[[-15744.98150019 -63187.59545228]
 [ 18520.37872802  15744.98150019]]
1482
[[  9269.28813557 -32700.45733552]
 [119881.0176104   -9269.28813557]]
[[  9269.28813557 -32700.45733552]
 [119881.0176104   -9269.28813557]]
1483
[[  9746.18453971  85488.45642894]
 [-97369.77214549  -9746.18453971]]
[[  9746.18453971  85488.45642894]
 [-97369.77214549  -9746.18453971]]
1484
[[-15437.70471684 -19007.50544121]
 [-61874.14856045  15437.70471684]]
[[-15437.70471684 -19007.50544121]
 [-61874.14856045  15437.70471684]]
1485
[[ -1275.72299216 -75724.86883108]
 [133382.91909549   1275.72299216]]
[[ -1275.72299216 -75724.86883108]
 [133382.91909549   1275.72299216]]
1486
[[ 16153.06810071  58313.25832798]
 [ -6209.62455339 -16153.06810071]]
[[ 16153.06810071  58313.25832798]
 [ -6209.62455339 -16153.06810071]]
1487
[[  -6384.97694391   49208.14581693]
 [-131761.01801987    6384.97694391]]
[[  -6384.97694391   49208.14581693]
 

 [152317.83219578  -1736.24615813]]
1540
[[ 10026.33088349 -39487.23960475]
 [137316.6176668  -10026.33088349]]
[[ 10026.33088349 -39487.23960475]
 [137316.6176668  -10026.33088349]]
1541
[[ 15818.84613905   3422.41086949]
 [ 93975.9562211  -15818.84613905]]
[[ 15818.84613905   3422.41086949]
 [ 93975.9562211  -15818.84613905]]
1542
[[ 18333.25149263  43636.37910482]
 [ 34929.90030817 -18333.25149263]]
[[ 18333.25149263  43636.37910482]
 [ 34929.90030817 -18333.25149263]]
1543
[[ 17626.33144592  74446.58361273]
 [-26960.74455282 -17626.33144592]]
[[ 17626.33144592  74446.58361273]
 [-26960.74455282 -17626.33144592]]
1544
[[ 14334.442538    92501.70754483]
 [-81426.16039801 -14334.442538  ]]
[[ 14334.442538    92501.70754483]
 [-81426.16039801 -14334.442538  ]]
1545
[[   9371.0828694    97465.0277882 ]
 [-122062.25309659   -9371.0828694 ]]
[[   9371.0828694    97465.0277882 ]
 [-122062.25309659   -9371.0828694 ]]
1546
[[   3669.44977784   91143.77291083]
 [-146336.00207423   -3669.44977

1614
[[   8182.64774161  110226.97246746]
 [-153361.57350349   -8182.64774161]]
[[   8182.64774161  110226.97246746]
 [-153361.57350349   -8182.64774161]]
1615
[[ 20469.92471109  31624.31933984]
 [ 70827.91270709 -20469.92471109]]
[[ 20469.92471109  31624.31933984]
 [ 70827.91270709 -20469.92471109]]
1616
[[  -4282.95493375 -104694.89440733]
 [ 168357.44557361    4282.95493375]]
[[  -4282.95493375 -104694.89440733]
 [ 168357.44557361    4282.95493375]]
1617
[[-21284.88394127 -46833.61157576]
 [-46990.06764923  21284.88394127]]
[[-21284.88394127 -46833.61157576]
 [-46990.06764923  21284.88394127]]
1618
[[   2296.32618633  101017.27490864]
 [-173420.07219729   -2296.32618633]]
[[   2296.32618633  101017.27490864]
 [-173420.07219729   -2296.32618633]]
1619
[[ 21378.94034044  50819.71384682]
 [ 40802.01975611 -21378.94034044]]
[[ 21378.94034044  50819.71384682]
 [ 40802.01975611 -21378.94034044]]
1620
[[  -2737.94477036 -102184.00368002]
 [ 173447.89245957    2737.94477036]]
[[  -2737.9447

1680
[[ -12655.81569282 -126874.72670477]
 [ 156747.39616186   12655.81569282]]
[[ -12655.81569282 -126874.72670477]
 [ 156747.39616186   12655.81569282]]
1681
[[  14761.78452942  126687.71076183]
 [-142435.64928159  -14761.78452942]]
[[  14761.78452942  126687.71076183]
 [-142435.64928159  -14761.78452942]]
1682
[[ -17351.9699837  -124212.46390603]
 [ 122089.42737597   17351.9699837 ]]
[[ -17351.9699837  -124212.46390603]
 [ 122089.42737597   17351.9699837 ]]
1683
[[ 19853.10061188 118176.57512372]
 [-94378.42065338 -19853.10061188]]
[[ 19853.10061188 118176.57512372]
 [-94378.42065338 -19853.10061188]]
1684
[[ -22285.25004231 -106976.70481528]
 [  58771.62991075   22285.25004231]]
[[ -22285.25004231 -106976.70481528]
 [  58771.62991075   22285.25004231]]
1685
[[ 23880.41542031  89335.46946683]
 [-15160.87093648 -23880.41542031]]
[[ 23880.41542031  89335.46946683]
 [-15160.87093648 -23880.41542031]]
1686
[[-24479.56958274 -64205.78818209]
 [-34815.61319784  24479.56958274]]
[[-24479.5

 [223812.2538391   -8885.90179736]]
[[  8885.90179736 -89767.9308373 ]
 [223812.2538391   -8885.90179736]]
1752
[[ 26872.80938498  49474.26607185]
 [ 78050.25944464 -26872.80938498]]
[[ 26872.80938498  49474.26607185]
 [ 78050.25944464 -26872.80938498]]
1753
[[  19822.7896206   141141.73843223]
 [-137369.83578972  -19822.7896206 ]]
[[  19822.7896206   141141.73843223]
 [-137369.83578972  -19822.7896206 ]]
1754
[[  -4430.4515227   108334.8698813 ]
 [-229594.83574575    4430.4515227 ]]
[[  -4430.4515227   108334.8698813 ]
 [-229594.83574575    4430.4515227 ]]
1755
[[ -24651.7780829   -13150.99706255]
 [-131054.43799989   24651.7780829 ]]
[[ -24651.7780829   -13150.99706255]
 [-131054.43799989   24651.7780829 ]]
1756
[[ -25375.25848006 -122158.39927794]
 [  67525.65472612   25375.25848006]]
[[ -25375.25848006 -122158.39927794]
 [  67525.65472612   25375.25848006]]
1757
[[  -7557.2380913  -139647.68210285]
 [ 212793.22040812    7557.2380913 ]]
[[  -7557.2380913  -139647.68210285]
 [ 212793

[[ -31645.49623159 -104053.200722  ]
 [  -5866.81490211   31645.49623159]]
[[ -31645.49623159 -104053.200722  ]
 [  -5866.81490211   31645.49623159]]
1834
[[  -8080.85610753  113272.41066106]
 [-261880.34567397    8080.85610753]]
[[  -8080.85610753  113272.41066106]
 [-261880.34567397    8080.85610753]]
1835
[[ 29611.27958998 135708.83122659]
 [-65346.63398899 -29611.27958998]]
[[ 29611.27958998 135708.83122659]
 [-65346.63398899 -29611.27958998]]
1836
[[ 14316.46996569 -85316.0490978 ]
 [249855.82957737 -14316.46996569]]
[[ 14316.46996569 -85316.0490978 ]
 [249855.82957737 -14316.46996569]]
1837
[[ -27708.32956997 -149282.0852737 ]
 [ 103322.27559405   27708.32956997]]
[[ -27708.32956997 -149282.0852737 ]
 [ 103322.27559405   27708.32956997]]
1838
[[ -16936.61026391   72444.59498511]
 [-241790.10039979   16936.61026391]]
[[ -16936.61026391   72444.59498511]
 [-241790.10039979   16936.61026391]]
1839
[[  27257.23649263  151899.55275358]
 [-110406.8843962   -27257.23649263]]
[[  27257.2

[[ -35984.69983825 -104004.50896217]
 [ -33396.72306446   35984.69983825]]
1908
[[ 3.02780725e+04  1.31698586e+02]
 [ 1.91542431e+05 -3.02780725e+04]]
[[ 3.02780725e+04  1.31698586e+02]
 [ 1.91542431e+05 -3.02780725e+04]]
1909
[[ -13614.59903538  109150.43028782]
 [-289191.17754309   13614.59903538]]
[[ -13614.59903538  109150.43028782]
 [-289191.17754309   13614.59903538]]
1910
[[  -9380.6184627  -180545.18056895]
 [ 277482.89408667    9380.6184627 ]]
[[  -9380.6184627  -180545.18056895]
 [ 277482.89408667    9380.6184627 ]]
1911
[[  29188.81961226  176956.36615749]
 [-144890.33695473  -29188.81961226]]
[[  29188.81961226  176956.36615749]
 [-144890.33695473  -29188.81961226]]
1912
[[-36163.71666256 -89332.23672523]
 [-61873.18375956  36163.71666256]]
[[-36163.71666256 -89332.23672523]
 [-61873.18375956  36163.71666256]]
1913
[[ 24615.29818251 -47806.18891263]
 [245074.54722362 -24615.29818251]]
[[ 24615.29818251 -47806.18891263]
 [245074.54722362 -24615.29818251]]
1914
[[    978.3445

**From the above code it is clear that Gauss' law is conserved throughout the simulation.**

**Now check if the Hamiltonian is conserved.**


In [98]:
# Define the Lagrangian

def L(X_list, V_list, g):
    
    X_array = np.array(X_list)
    V_array = np.array(X_list)
    term_1 =  np.sum( np.trace( (V_array)**2 ) )
    
    # Calculate the sum of commutators found in the second term of the lagrangian
    for el in X_list:
        X_cut = [x for x in X_list if x != el]
        Sum2 = np.sum( np.trace( (commutator(el,X_cut))**2 ) ) 
    
    term_2 = 1/2 * Sum2
    
    return 1/(2*g**2) * (term_1 + term_2)

# Define the Hamiltonian

def H(X_list, V_list, g):
    
    
    X_array = np.array(X_list)
    V_array = np.array(X_list)
    term_1 =  np.sum( np.trace( (V_array)**2 ) )
    
    # Calculate the sum of commutators found in the second term of the lagrangian
    for el in X_list:
        X_cut = [x for x in X_list if x != el]
        Sum2 = np.sum( np.trace( (commutator(el,X_cut))**2 ) ) 
    
    term_2 = 1/2 * Sum2
    
    return 1/(2*g**2) * (term_1 - term_2)
    

In [99]:
X2

X 1  \
0                     [[-25.638812687739993, -91.76627763573693], [-...   
0.009999999999999998  [[-25.638336533779736, -91.76651651917533], [-...   
0.019999999999999997  [[-25.637748375612812, -91.7665779036196], [-7...   
0.03                  [[-25.637050262750538, -91.76646503673459], [-...   
0.039999999999999994  [[-25.636244450645783, -91.76618149253375], [-...   
0.049999999999999996  [[-25.635333396497664, -91.76573116473581], [-...   
0.06                  [[-25.63431975467819, -91.76511825952142], [-7...   
0.06999999999999999   [[-25.63320637178904, -91.76434728770421], [-7...   
0.07999999999999999   [[-25.631996281358198, -91.76342305633099], [-...   
0.09                  [[-25.630692698185307, -91.76235065972607], [-...   

                                                                    X 2  
0                     [[59.17941552987677, 208.75047881451303], [171...  
0.009999999999999998  [[59.18100864431433, 208.75526669847144], [171...  
0.019999999999999997  [[59.18265095740752, 208.76013259606927], [171...  
0.03                  [[59.18434156846955, 208.7650750784062], [171....  
0.039999999999999994  [[59.186079486328325, 208.77009257306216], [17...  
0.049999999999999996  [[59.187863631175, 208.7751833670365], [171.24...  
0.06                  [[59.18969283657943, 208.78034560995542], [171...  
0.06999999999999999   [[59.19156585166818, 208.7855773175364], [171....  
0.07999999999999999   [[59.19348134346092, 208.79087637530415], [171...  
0.09                  [[59.195437899361714, 208.79624054255325], [17...

In [100]:
i = 0
while i < len(X_test["X 1"].values):
    
    # Create a list of the two coordinate matrices for the position.
    X_list = [X_test["X 1"].values[i], X_test["X 2"].values[i]]
    V_list = [V_test["V 1"].values[i], V_test["V 2"].values[i]]

    
    print(H(X_list, V_list, 1))
    i += 1

1.4111887085271713
1.4079754630121775
1.3983273496559394
1.3822213758308473
1.359626363005623
1.3305136943925078
1.2948723475138877
1.2527280207577505
1.204165891318386
1.149356165693222
1.088581136857644
1.022262000939069
0.9509832839624437
0.8755124658827573
0.7968123378277162
0.7160438415301541
0.6345576362217425
0.5538733953292247
0.47564678829015045
0.40162515123717546
0.3335938722246514
0.27331638748474557
0.2224712976850886
0.1825903946228203
0.15500131190155642
0.14077809852633227
0.1407023248857518
0.15523645906934763
0.1845103046499146
0.2283203733700962
0.28614126601938217
0.35714751543885953
0.4402439413075592
0.5341023833716125
0.6372027008349889
0.7478761165935557
0.8643493017993773
0.9847879910716385
1.107339344515268
1.2301726860343196
1.3515186090478544
1.4697067152765366
1.5832024069329016
1.6906431557176498
1.7908744922999338
1.882985567772994
1.9663435094931458
2.040624915938807
2.1058417216269403
2.1623573681743236
2.2108878585384337
2.2524810508517183
2.2884667718

2129.520648433834
2409.7199326302525
2120.3980781184764
2447.9819257227523
2170.9311102810666
2449.830628074031
2192.0009460574493
2479.818410046001
2242.7349289886693
2485.0658540706513
2254.2411562670895
2531.9516753143284
2288.242597140764
2554.8329722741505
2284.454608960005
2609.5175769676734
2319.501549308457
2629.199933923123
2333.050989716329
2642.2577607736785
2423.5413519548742
2605.381573179987
2512.2990465630683
2528.5495580564375
2668.2056408845
2469.007323352334
2753.573011316928
2450.898153698449
2758.3351531170288
2597.0348090986986
2643.6979473685356
2767.594489342175
2526.5250134099533
2865.5625228910503
2628.548848388963
2740.6752329418005
2838.462285501449
2592.676458359173
2925.006234335513
2754.3659828554732
2737.758934710924
2975.207627521042
2683.581432135855
2878.583874531968
2987.886744173093
2726.0393566618823
2989.6615251846188
2968.644774128029
2753.002552932412
3060.0590240039487
3023.040638336961
2818.218848955473
3096.108617987605
3074.2338682167424
2840

70232.35097914348
70360.94180163252
70513.99005418413
70685.58849528214
70877.64674731238
71099.69532377188
71367.2872195349
71697.93308693262
72103.14397645964
72575.9713702472
73076.34269145752
73521.86377654927
73797.76052394196
73800.29933787131
73513.8000949936
73086.5628824276
72830.01950903983
73065.68134729366
73845.125004579
74756.81828123146
75130.63195248539
74681.90523745681
74019.82677615131
74178.28561331097
75284.18535172034
76062.47745532
75506.83085095053
74723.58621288369
75422.48893349951
76690.3175078518
76333.5018694593
75448.76603982461
76467.98862760128
77455.5377056994
76346.15210097891
76413.27164149968
77963.02216915887
77153.95551169533
76915.91623624082
78543.61640098311
77483.37436149795
77687.80369126284
79020.06648388221
77620.81574564775
79069.26749294148
78809.57354482064
78441.23549567914
79893.20114391389
78477.06707934209
80346.00605479607
78948.6976887938
80423.3064444635
79611.2194039736
80618.70659852879
80090.90632212242
80895.54197144885
80430.4

**From derivation in page**

# Check conservation of angular momentum

**Angular momentum is $Tr(Xi\dot Xj - Xj\dot Xi)$**

In [101]:
def angular_momentum(X2_by_2, V2_by_2):
    
    i = 0
    while i < len(X2_by_2):
        
        Xi = X2_by_2[i]
        Vi = V2_by_2[i]
        np.sum(np.trace( np.matmul(Xi, V2_by_2) - np.matmul(X2_by_2, Vi) ))
        
        i += 1

In [102]:
angular_momentum(X2_by_2, V2_by_2)

KeyError: 0

In [ ]:
X_test["X 1"][0]

In [ ]:
plt.figure(figsize = (15,10))

i = 0

X1_values = []
V1_values = []
while i < len(X_test["X 1"]):
    X1_values.append(X_test["X 1"].values[i][0][0])
    V1_values.append(V_test["V 1"].values[i][0][0])

    i += 1
plt.subplot(2,2,1)
plt.plot(X1_values, V1_values)
plt.xlabel("X 1 entry 1")
plt.ylabel("P 1 entry 1")
i = 0
X2_values = []
V2_values = []
while i < len(X_test["X 1"]):
    X2_values.append(X_test["X 1"].values[i][0][1])
    V2_values.append(V_test["V 1"].values[i][0][1])

    i += 1
plt.subplot(2,2,2)

plt.plot(X2_values, V2_values)
plt.xlabel("X 1 entry 2")
plt.ylabel("P 1 entry 2")


i = 0
X3_values = []
V3_values = []
while i < len(X_test["X 1"]):
    X3_values.append(X_test["X 1"].values[i][1][0])
    V3_values.append(V_test["V 1"].values[i][1][0])

    i += 1
plt.subplot(2,2,3)
plt.plot(X3_values, V3_values)
plt.xlabel("X 1 entry 3")
plt.ylabel("P 1 entry 3")


i = 0
X4_values = []
V4_values = []
while i < len(X_test["X 1"]):
    X4_values.append(X_test["X 1"].values[i][1][1])
    V4_values.append(V_test["V 1"].values[i][1][1])

    i += 1
plt.subplot(2,2,4)
plt.plot(X4_values, V4_values)
plt.xlabel("X 1 entry 4")
plt.ylabel("P 1 entry 4")







In [ ]:
plt.figure(figsize = (15,10))

i = 0

X1_values = []
V1_values = []
while i < len(X_test["X 2"]):
    X1_values.append(X_test["X 2"].values[i][0][0])
    V1_values.append(V_test["V 2"].values[i][0][0])

    i += 1
plt.subplot(2,2,1)
plt.plot(X1_values, V1_values)
plt.xlabel("X 2 entry 1")
plt.ylabel("P 2 entry 1")
i = 0
X2_values = []
V2_values = []
while i < len(X_test["X 2"]):
    X2_values.append(X_test["X 2"].values[i][0][1])
    V2_values.append(V_test["V 2"].values[i][0][1])

    i += 1
plt.subplot(2,2,2)

plt.plot(X2_values, V2_values)
plt.xlabel("X 2 entry 2")
plt.ylabel("P 2 entry 2")


i = 0
X3_values = []
V3_values = []
while i < len(X_test["X 2"]):
    X3_values.append(X_test["X 2"].values[i][1][0])
    V3_values.append(V_test["V 2"].values[i][1][0])

    i += 1
plt.subplot(2,2,3)
plt.plot(X3_values, V3_values)
plt.xlabel("X 2 entry 3")
plt.ylabel("P 2 entry 3")


i = 0
X4_values = []
V4_values = []
while i < len(X_test["X 2"]):
    X4_values.append(X_test["X 2"].values[i][1][1])
    V4_values.append(V_test["V 2"].values[i][1][1])

    i += 1
plt.subplot(2,2,4)
plt.plot(X4_values, V4_values)
plt.xlabel("X 2 entry 4")
plt.ylabel("P 2 entry 4")



In [ ]:
delta_t = 10**-4
record_steps = 100
simulation_repetitions = 200000
times = np.arange(delta_t*record_steps, simulation_repetitions*delta_t + delta_t*record_steps, delta_t*record_steps)


In [ ]:
plt.figure(figsize = (15,10))

i = 0

X1_values = []
V1_values = []
while i < len(X_test["X 1"]):
    X1_values.append(X_test["X 1"].values[i][0][0])
    V1_values.append(V_test["V 1"].values[i][0][0])

    i += 1
plt.subplot(2,2,1)
plt.plot(times, X1_values)
plt.ylabel("X 1 entry 1")
plt.xlabel("times")
i = 0
X2_values = []
V2_values = []
while i < len(X_test["X 1"]):
    X2_values.append(X_test["X 1"].values[i][0][1])
    V2_values.append(V_test["V 1"].values[i][0][1])

    i += 1
plt.subplot(2,2,2)

plt.plot(times, X2_values)
plt.ylabel("X 1 entry 2")
plt.xlabel("times")


i = 0
X3_values = []
V3_values = []
while i < len(X_test["X 1"]):
    X3_values.append(X_test["X 1"].values[i][1][0])
    V3_values.append(V_test["V 1"].values[i][1][0])

    i += 1
plt.subplot(2,2,3)
plt.plot(times, X3_values)
plt.ylabel("X 1 entry 3")
plt.xlabel("times")


i = 0
X4_values = []
V4_values = []
while i < len(X_test["X 1"]):
    X4_values.append(X_test["X 1"].values[i][1][1])
    V4_values.append(V_test["V 1"].values[i][1][1])

    i += 1
plt.subplot(2,2,4)
plt.plot(times, X4_values)
plt.ylabel("X 1 entry 4")
plt.xlabel("times")




# L2 norm


In [ ]:
i = 0
X1_norms = []
while i < len(X_test["X 1"]):
    X1_norms.append(norm(V_test["V 2"][i]))
    i += 1

In [ ]:
plt.plot(times, X1_norms)
plt.yscale("log")

# Lyapunov exponent

**Using the l_2 for the separation.**

In [103]:
X_style = np.loadtxt(path+'"X_vector_initial.txt', delimiter = " ")

OSError: C:/Users/robtk/OneDrive/Desktop/DIAS Internship/Raw data/Harmonic oscillator warm up/"X_vector_initial.txt not found.

In [145]:
# Load in each line in the text file
X_list3 = pd.read_csv(path + "X_vector_test.txt",
                        names = ["X1"],
                      index_col=False)
X_list3["X1"]


0       0.004140886653359  0.002255679494230  0.02539...
1       0.002255679494230  0.004134642313233  0.01469...
2       0.025393301532669  0.014692932980840 -0.00827...
3      -0.002180561068472 -0.005458123775600  0.00077...
4      -0.005458123775600 -0.004325012936413 -0.00666...
                             ...                        
292     0.014360287854421  0.000032766825443  0.01488...
293     0.012737715997033  0.014882882892204  0.01537...
294    -0.003534490614896  0.013681672148115 -0.00147...
295     0.013681672148115  0.001200771111124  0.00830...
296    -0.001471002246167  0.008306846518448  0.00233...
Name: A1, Length: 297, dtype: object

In [149]:
# Split each line into a list in a list
data = []
for line in A_list3["A1"]:
    items = line.rstrip('\n').split(" ")
    data.append(items)
i = 0
while i < len(data):
    
    data[i] = list(filter(None, data[i]))
    i += 1


In [156]:
# Turn each element into a float
np.array(data, dtype=np.float32)

array([[ 4.14088648e-03,  2.25567957e-03,  2.53933016e-02],
       [ 2.25567957e-03,  4.13464243e-03,  1.46929333e-02],
       [ 2.53933016e-02,  1.46929333e-02, -8.27552937e-03],
       [-2.18056096e-03, -5.45812398e-03,  7.72220839e-04],
       [-5.45812398e-03, -4.32501314e-03, -6.66948082e-03],
       [ 7.72220839e-04, -6.66948082e-03,  6.50557410e-03],
       [-9.64318495e-03, -1.78274531e-02,  7.02030305e-03],
       [-1.78274531e-02,  2.61085946e-03, -1.47984468e-03],
       [ 7.02030305e-03, -1.47984468e-03,  7.03232503e-03],
       [ 1.00265276e-02, -9.30505805e-03,  1.82542782e-02],
       [-9.30505805e-03, -4.24288725e-03,  4.42498131e-03],
       [ 1.82542782e-02,  4.42498131e-03, -5.78363985e-03],
       [ 6.08499860e-03,  3.43276188e-03, -1.19322557e-02],
       [ 3.43276188e-03,  1.24999890e-02, -6.56892173e-03],
       [-1.19322557e-02, -6.56892173e-03, -1.85849871e-02],
       [ 6.32952852e-03,  5.19429520e-03, -1.41143944e-04],
       [ 5.19429520e-03, -9.28482786e-03

In [ ]:
# Turn every 

In [ ]:
A_list3 = pd.read_csv(path + "A_vector_initial.txt", sep = ";",
                        names = ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9"],
                      index_col=False)

In [30]:
X_list3 = pd.read_csv(path + "X_vector_initial.txt", sep = "\s+;,",
                      names = ["X1", "X2", "X3", "X4", "X5", "X6", "X7", "X8", "X9"],
                      index_col=False)
X_list3["X1"][0]

<ipython-input-30-9f5b6aa4e332>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  X_list3 = pd.read_csv(path + "X_vector_initial.txt", sep = "\s+;,",


'0.414088665335914,0.225567949423011,0.413464231323263,-2.539330153266858,-0.218056106847159,0.545812377560037,;0.413464231323263,2.539330153266858,1.469293298084035,0.145926865506495,-0.432501293641333,-0.077222086347351,;-0.218056106847159,-0.545812377560037,-0.432501293641333,0.077222086347351,-1.883381963419949,-0.371494814929506,;'