In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas import DataFrame as DF
from sympy import diff
from sympy.abc import x,y
from sympy import cos
from sympy import *
from sympy import lambdify
from itertools import product
import random
from scipy.linalg import norm

**Define path.**

In [5]:
# Defining path to folder raw data is saved in
path = "C:/Users/robtk/OneDrive/Desktop/DIAS Internship/Raw data/Harmonic oscillator warm up/"

### Set display of pandas dataframes and Series to 11 decimal places

In [6]:
pd.set_option("display.precision", 11)

**Read in the outputs for 2 2x2 matrices**

In [7]:
X2_by_2 = pd.read_pickle(path+"X.pkl")
V2_by_2 = pd.read_pickle(path+"V.pkl")

X2 = pd.read_pickle(path+"Xb.pkl")
V2 = pd.read_pickle(path+"Vb.pkl")

X_test = pd.read_pickle(path+"X_test.pkl")
V_test = pd.read_pickle(path+"V_test.pkl")

X_test = pd.read_pickle(path+"X_test9.pkl")
V_test = pd.read_pickle(path+"V_test9.pkl")


**Check that the Gauss' law constraint is conserved.**

In [8]:
X2_by_2

X 1  \
0                  [[-1.2648031177873595, 0.28965090823750295], [...   
0.1                [[-1.266024586128383, 0.3075498233453539], [0....   
0.2                [[-1.2672461453989399, 0.3254499316527957], [0...   
0.3                [[-1.2684206793138693, 0.3427458500505543], [0...   
0.4                [[-1.2695023596759814, 0.3588490235768357], [0...   
...                                                              ...   
9.5                [[-1.2553307128237747, 0.3864624075261496], [0...   
9.6                [[-1.256553976865044, 0.4045837340315353], [0....   
9.700000000000001  [[-1.2576228624582029, 0.4207220073740257], [0...   
9.8                [[-1.2584778821555025, 0.43411357363433767], [...   
9.9                [[-1.2590696112331297, 0.4441241603022393], [0...   

                                                                 X 2  
0                  [[-0.988786234734847, -8.808868141843881], [-9...  
0.1                [[-0.9924837407927861, -8.82448803046022], [-9...  
0.2                [[-0.9961812908590642, -8.840108058987312], [-...  
0.3                [[-0.9998774849649374, -8.855750406355776], [-...  
0.4                [[-1.0035714229022201, -8.871438686484098], [-...  
...                                                              ...  
9.5                [[-1.3513982692174915, -10.418536239755582], [...  
9.6                [[-1.3554268690283275, -10.435619594516812], [...  
9.700000000000001  [[-1.3594517279362057, -10.452779362294871], [...  
9.8                [[-1.3634722119282914, -10.47004855952829], [-...  
9.9                [[-1.3674881329031612, -10.487456115722527], [...  

[100 rows x 2 columns]

In [9]:
# Define the commutator
def commutator(A,B):
    
    # matmul() multiplies two matrices together
    return np.matmul(A,B) - np.matmul(B,A)

## Are Xi still traceless

## Gauss' Law test

In [111]:
i = 0
while i < len(X_DF.iloc[:,0]):
    
    # Computes the sum of the commutators of Xi and Vi and if they equal zero move on to the next one.
    
    Gauss = (commutator(np.array(X_DF.iloc[i,0]), np.array(V_DF.iloc[i,0])) + 
             commutator(np.array(X_DF.iloc[i,1]), np.array(V_DF.iloc[i,1])) +
             commutator(np.array(X_DF.iloc[i,2]), np.array(V_DF.iloc[i,2])) + 
             commutator(np.array(X_DF.iloc[i,3]), np.array(V_DF.iloc[i,3])) +
             commutator(np.array(X_DF.iloc[i,4]), np.array(V_DF.iloc[i,4])) + 
             commutator(np.array(X_DF.iloc[i,5]), np.array(V_DF.iloc[i,5])) + 
             commutator(np.array(X_DF.iloc[i,6]), np.array(V_DF.iloc[i,6])) + 
             commutator(np.array(X_DF.iloc[i,7]), np.array(V_DF.iloc[i,7])) + 
             commutator(np.array(X_DF.iloc[i,8]), np.array(V_DF.iloc[i,8])) )

             
             
    i+=1
    print(i)
    # Check if the answer equals the zero matrix.
    if np.all(np.isclose(Gauss, 0)) != True:
        
    # If the sum is printed then the commutator does not equal the zero matrix stop the loop and print what the answer is.
        print(Gauss)
        
    print(Gauss)

1
[[ 0.00000000e+00  3.60126257e-05  2.41292888e-05]
 [-3.60126257e-05  0.00000000e+00  1.61952639e-05]
 [-2.41292888e-05 -1.61952639e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60126257e-05  2.41292888e-05]
 [-3.60126257e-05  0.00000000e+00  1.61952639e-05]
 [-2.41292888e-05 -1.61952639e-05  0.00000000e+00]]
2
[[ 0.00000000e+00  3.60128471e-05  2.41294405e-05]
 [-3.60128471e-05  0.00000000e+00  1.61953652e-05]
 [-2.41294405e-05 -1.61953652e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128471e-05  2.41294405e-05]
 [-3.60128471e-05  0.00000000e+00  1.61953652e-05]
 [-2.41294405e-05 -1.61953652e-05  0.00000000e+00]]
3
[[ 0.00000000e+00  3.60128480e-05  2.41294396e-05]
 [-3.60128480e-05  0.00000000e+00  1.61953637e-05]
 [-2.41294396e-05 -1.61953637e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128480e-05  2.41294396e-05]
 [-3.60128480e-05  0.00000000e+00  1.61953637e-05]
 [-2.41294396e-05 -1.61953637e-05  0.00000000e+00]]
4
[[ 0.00000000e+00  3.60128470e-05  2.41294399e-05]
 [-3.60128470e-05

125
[[ 0.00000000e+00  3.60128477e-05  2.41294403e-05]
 [-3.60128477e-05  0.00000000e+00  1.61953647e-05]
 [-2.41294403e-05 -1.61953647e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128477e-05  2.41294403e-05]
 [-3.60128477e-05  0.00000000e+00  1.61953647e-05]
 [-2.41294403e-05 -1.61953647e-05  0.00000000e+00]]
126
[[ 0.00000000e+00  3.60128487e-05  2.41294405e-05]
 [-3.60128487e-05  0.00000000e+00  1.61953643e-05]
 [-2.41294405e-05 -1.61953643e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128487e-05  2.41294405e-05]
 [-3.60128487e-05  0.00000000e+00  1.61953643e-05]
 [-2.41294405e-05 -1.61953643e-05  0.00000000e+00]]
127
[[ 0.00000000e+00  3.60128475e-05  2.41294403e-05]
 [-3.60128475e-05  0.00000000e+00  1.61953639e-05]
 [-2.41294403e-05 -1.61953639e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128475e-05  2.41294403e-05]
 [-3.60128475e-05  0.00000000e+00  1.61953639e-05]
 [-2.41294403e-05 -1.61953639e-05  0.00000000e+00]]
128
[[ 0.00000000e+00  3.60128483e-05  2.41294407e-05]
 [-3.6012

260
[[ 0.00000000e+00  3.60128480e-05  2.41294409e-05]
 [-3.60128480e-05  0.00000000e+00  1.61953656e-05]
 [-2.41294409e-05 -1.61953656e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128480e-05  2.41294409e-05]
 [-3.60128480e-05  0.00000000e+00  1.61953656e-05]
 [-2.41294409e-05 -1.61953656e-05  0.00000000e+00]]
261
[[ 0.00000000e+00  3.60128480e-05  2.41294401e-05]
 [-3.60128480e-05  0.00000000e+00  1.61953645e-05]
 [-2.41294401e-05 -1.61953645e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128480e-05  2.41294401e-05]
 [-3.60128480e-05  0.00000000e+00  1.61953645e-05]
 [-2.41294401e-05 -1.61953645e-05  0.00000000e+00]]
262
[[ 0.00000000e+00  3.60128478e-05  2.41294395e-05]
 [-3.60128478e-05  0.00000000e+00  1.61953637e-05]
 [-2.41294395e-05 -1.61953637e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128478e-05  2.41294395e-05]
 [-3.60128478e-05  0.00000000e+00  1.61953637e-05]
 [-2.41294395e-05 -1.61953637e-05  0.00000000e+00]]
263
[[ 0.00000000e+00  3.60128478e-05  2.41294399e-05]
 [-3.6012

390
[[ 0.00000000e+00  3.60128466e-05  2.41294399e-05]
 [-3.60128466e-05  0.00000000e+00  1.61953643e-05]
 [-2.41294399e-05 -1.61953643e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128466e-05  2.41294399e-05]
 [-3.60128466e-05  0.00000000e+00  1.61953643e-05]
 [-2.41294399e-05 -1.61953643e-05  0.00000000e+00]]
391
[[ 0.00000000e+00  3.60128478e-05  2.41294402e-05]
 [-3.60128478e-05  0.00000000e+00  1.61953647e-05]
 [-2.41294402e-05 -1.61953647e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128478e-05  2.41294402e-05]
 [-3.60128478e-05  0.00000000e+00  1.61953647e-05]
 [-2.41294402e-05 -1.61953647e-05  0.00000000e+00]]
392
[[ 0.00000000e+00  3.60128476e-05  2.41294392e-05]
 [-3.60128476e-05  0.00000000e+00  1.61953640e-05]
 [-2.41294392e-05 -1.61953640e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128476e-05  2.41294392e-05]
 [-3.60128476e-05  0.00000000e+00  1.61953640e-05]
 [-2.41294392e-05 -1.61953640e-05  0.00000000e+00]]
393
[[ 0.00000000e+00  3.60128481e-05  2.41294398e-05]
 [-3.6012

[[ 0.00000000e+00  3.60128481e-05  2.41294420e-05]
 [-3.60128481e-05  0.00000000e+00  1.61953639e-05]
 [-2.41294420e-05 -1.61953639e-05  0.00000000e+00]]
526
[[ 0.00000000e+00  3.60128486e-05  2.41294401e-05]
 [-3.60128486e-05  0.00000000e+00  1.61953652e-05]
 [-2.41294401e-05 -1.61953652e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128486e-05  2.41294401e-05]
 [-3.60128486e-05  0.00000000e+00  1.61953652e-05]
 [-2.41294401e-05 -1.61953652e-05  0.00000000e+00]]
527
[[ 0.00000000e+00  3.60128475e-05  2.41294377e-05]
 [-3.60128475e-05  0.00000000e+00  1.61953634e-05]
 [-2.41294377e-05 -1.61953634e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128475e-05  2.41294377e-05]
 [-3.60128475e-05  0.00000000e+00  1.61953634e-05]
 [-2.41294377e-05 -1.61953634e-05  0.00000000e+00]]
528
[[ 0.00000000e+00  3.60128476e-05  2.41294418e-05]
 [-3.60128476e-05  0.00000000e+00  1.61953633e-05]
 [-2.41294418e-05 -1.61953633e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128476e-05  2.41294418e-05]
 [-3.60128476

632
[[ 0.00000000e+00  3.60128487e-05  2.41294399e-05]
 [-3.60128487e-05  0.00000000e+00  1.61953634e-05]
 [-2.41294399e-05 -1.61953634e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128487e-05  2.41294399e-05]
 [-3.60128487e-05  0.00000000e+00  1.61953634e-05]
 [-2.41294399e-05 -1.61953634e-05  0.00000000e+00]]
633
[[ 0.00000000e+00  3.60128483e-05  2.41294406e-05]
 [-3.60128483e-05  0.00000000e+00  1.61953656e-05]
 [-2.41294406e-05 -1.61953656e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128483e-05  2.41294406e-05]
 [-3.60128483e-05  0.00000000e+00  1.61953656e-05]
 [-2.41294406e-05 -1.61953656e-05  0.00000000e+00]]
634
[[ 0.00000000e+00  3.60128468e-05  2.41294393e-05]
 [-3.60128468e-05  0.00000000e+00  1.61953642e-05]
 [-2.41294393e-05 -1.61953642e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128468e-05  2.41294393e-05]
 [-3.60128468e-05  0.00000000e+00  1.61953642e-05]
 [-2.41294393e-05 -1.61953642e-05  0.00000000e+00]]
635
[[ 0.00000000e+00  3.60128470e-05  2.41294396e-05]
 [-3.6012

 [-2.41294405e-05 -1.61953649e-05  0.00000000e+00]]
767
[[ 0.00000000e+00  3.60128467e-05  2.41294391e-05]
 [-3.60128467e-05  0.00000000e+00  1.61953630e-05]
 [-2.41294391e-05 -1.61953630e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128467e-05  2.41294391e-05]
 [-3.60128467e-05  0.00000000e+00  1.61953630e-05]
 [-2.41294391e-05 -1.61953630e-05  0.00000000e+00]]
768
[[ 0.00000000e+00  3.60128475e-05  2.41294399e-05]
 [-3.60128475e-05  0.00000000e+00  1.61953639e-05]
 [-2.41294399e-05 -1.61953639e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128475e-05  2.41294399e-05]
 [-3.60128475e-05  0.00000000e+00  1.61953639e-05]
 [-2.41294399e-05 -1.61953639e-05  0.00000000e+00]]
769
[[ 0.00000000e+00  3.60128470e-05  2.41294403e-05]
 [-3.60128470e-05  0.00000000e+00  1.61953662e-05]
 [-2.41294403e-05 -1.61953662e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128470e-05  2.41294403e-05]
 [-3.60128470e-05  0.00000000e+00  1.61953662e-05]
 [-2.41294403e-05 -1.61953662e-05  0.00000000e+00]]
770
[[ 0.000

909
[[ 0.00000000e+00  3.60128462e-05  2.41294421e-05]
 [-3.60128462e-05  0.00000000e+00  1.61953632e-05]
 [-2.41294421e-05 -1.61953632e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128462e-05  2.41294421e-05]
 [-3.60128462e-05  0.00000000e+00  1.61953632e-05]
 [-2.41294421e-05 -1.61953632e-05  0.00000000e+00]]
910
[[ 0.00000000e+00  3.60128494e-05  2.41294406e-05]
 [-3.60128494e-05  0.00000000e+00  1.61953636e-05]
 [-2.41294406e-05 -1.61953636e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128494e-05  2.41294406e-05]
 [-3.60128494e-05  0.00000000e+00  1.61953636e-05]
 [-2.41294406e-05 -1.61953636e-05  0.00000000e+00]]
911
[[ 0.00000000e+00  3.60128493e-05  2.41294407e-05]
 [-3.60128493e-05  0.00000000e+00  1.61953654e-05]
 [-2.41294407e-05 -1.61953654e-05  0.00000000e+00]]
[[ 0.00000000e+00  3.60128493e-05  2.41294407e-05]
 [-3.60128493e-05  0.00000000e+00  1.61953654e-05]
 [-2.41294407e-05 -1.61953654e-05  0.00000000e+00]]
912
[[ 0.00000000e+00  3.60128457e-05  2.41294413e-05]
 [-3.6012

**From the above code it is clear that Gauss' law is conserved throughout the simulation.**

**Now check if the Hamiltonian is conserved.**


In [112]:
# Define the Lagrangian

def L(X_list, V_list, g):
    
    X_array = np.array(X_list)
    V_array = np.array(X_list)
    term_1 =  np.sum( np.trace( (V_array)**2 ) )
    
    # Calculate the sum of commutators found in the second term of the lagrangian
    for el in X_list:
        X_cut = [x for x in X_list if x != el]
        Sum2 = np.sum( np.trace( (commutator(el,X_cut))**2 ) ) 
    
    term_2 = 1/2 * Sum2
    
    return 1/(2*g**2) * (term_1 + term_2)

# Define the Hamiltonian

def H(X_list, V_list, g):
    
    
    X_array = np.array(X_list)
    V_array = np.array(X_list)
    term_1 =  np.sum( np.trace( (V_array)**2 ) )
    
    # Calculate the sum of commutators found in the second term of the lagrangian
    for el in X_list:
        X_cut = [x for x in X_list if x != el]
        Sum2 = np.sum( np.trace( (commutator(el,X_cut))**2 ) ) 
    
    term_2 = 1/2 * Sum2
    
    return 1/(2*g**2) * (term_1 - term_2)
    

In [81]:
i = 0
while i < len(X_DF["X1"].values):
    
    # Create a list of the 9 coordinate matrices for the position.
    X_list = [X_DF["X1"].values[i], X_DF["X2"].values[i], X_DF["X3"].values[i], X_DF["X4"].values[i], 
              X_DF["X5"].values[i], X_DF["X6"].values[i], X_DF["X7"].values[i], X_DF["X8"].values[i],
              X_DF["X9"].values[i]]
    V_list = [V_DF["V1"].values[i], V_DF["V2"].values[i], V_DF["V3"].values[i], V_DF["V4"].values[i], 
              V_DF["V5"].values[i], V_DF["V6"].values[i], V_DF["V7"].values[i], V_DF["V8"].values[i],
              V_DF["V9"].values[i]]

    
    print(H(X_list, V_list, 1))
    i += 1

0.0004304484016588111
0.0004304484016588111
0.0004280926776567442
0.0004211301768563846
0.0004098642264114583
0.00039477565680484477
0.0003764886356081441
0.0003557288527293563
0.0003332784352691802
0.00030993151775609407
0.00028645515649633024
0.00026355711592893424
0.00024186264155665835
0.00022190011798442198
0.0002040950304203923
0.00018877095313418046
0.00017615594599398795
0.00016639266795086065
0.0001595507775164648
0.00015564025347589494
0.00015462468681727294
0.00015643381985577524
0.00016097483768523325
0.0001681422103223422
0.00017782582543188568
0.0001899175994632416
0.00020431640735334597
0.0002209314821173035
0.00023968433886213306
0.0002605092363386133
0.0002833522644846393
0.00030816899501856737
0.0003349207523064168
0.0003635695606976667
0.0003940718262785966
0.00042637043236463745
0.00046038643149932354
0.0004960096293352579
0.000533088689337398
0.0005714224249869367
0.0006107512680149617
0.0006507519615314965
0.0006910347613273703
0.0007311453911157809
0.000770572756

**From derivation in page**

# Check conservation of angular momentum

**Angular momentum is $Tr(Xi\dot Xj - Xj\dot Xi)$**

In [126]:
def angular_momentum(X2_by_2, V2_by_2):
    
    i = 0
    while i < len(X_DF["X1"].values):
        # Create a list of the 9 coordinate matrices for the position.
        X_list = [X_DF["X1"].values[i], X_DF["X2"].values[i], X_DF["X3"].values[i], X_DF["X4"].values[i], 
                  X_DF["X5"].values[i], X_DF["X6"].values[i], X_DF["X7"].values[i], X_DF["X8"].values[i],
                  X_DF["X9"].values[i]]
        V_list = [V_DF["V1"].values[i], V_DF["V2"].values[i], V_DF["V3"].values[i], V_DF["V4"].values[i], 
                  V_DF["V5"].values[i], V_DF["V6"].values[i], V_DF["V7"].values[i], V_DF["V8"].values[i],
                  V_DF["V9"].values[i]]  
        i += 1
        
    i = 0
    while i < len(X_list):
        
        j = 0
        Sum = 0
        while j < len(X_list):
            Sum += np.trace( np.matmul(X_list[i], V_list[j]) - np.matmul(V_list[j], X_list[i]) )
            j += 1
        print(Sum)
        
        i += 1

In [127]:
angular_momentum(X2_by_2, V2_by_2)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [ ]:
X_test["X 1"][0]

In [ ]:
plt.figure(figsize = (15,10))

i = 0

X1_values = []
V1_values = []
while i < len(X_test["X 1"]):
    X1_values.append(X_test["X 1"].values[i][0][0])
    V1_values.append(V_test["V 1"].values[i][0][0])

    i += 1
plt.subplot(2,2,1)
plt.plot(X1_values, V1_values)
plt.xlabel("X 1 entry 1")
plt.ylabel("P 1 entry 1")
i = 0
X2_values = []
V2_values = []
while i < len(X_test["X 1"]):
    X2_values.append(X_test["X 1"].values[i][0][1])
    V2_values.append(V_test["V 1"].values[i][0][1])

    i += 1
plt.subplot(2,2,2)

plt.plot(X2_values, V2_values)
plt.xlabel("X 1 entry 2")
plt.ylabel("P 1 entry 2")


i = 0
X3_values = []
V3_values = []
while i < len(X_test["X 1"]):
    X3_values.append(X_test["X 1"].values[i][1][0])
    V3_values.append(V_test["V 1"].values[i][1][0])

    i += 1
plt.subplot(2,2,3)
plt.plot(X3_values, V3_values)
plt.xlabel("X 1 entry 3")
plt.ylabel("P 1 entry 3")


i = 0
X4_values = []
V4_values = []
while i < len(X_test["X 1"]):
    X4_values.append(X_test["X 1"].values[i][1][1])
    V4_values.append(V_test["V 1"].values[i][1][1])

    i += 1
plt.subplot(2,2,4)
plt.plot(X4_values, V4_values)
plt.xlabel("X 1 entry 4")
plt.ylabel("P 1 entry 4")







In [ ]:
plt.figure(figsize = (15,10))

i = 0

X1_values = []
V1_values = []
while i < len(X_test["X 2"]):
    X1_values.append(X_test["X 2"].values[i][0][0])
    V1_values.append(V_test["V 2"].values[i][0][0])

    i += 1
plt.subplot(2,2,1)
plt.plot(X1_values, V1_values)
plt.xlabel("X 2 entry 1")
plt.ylabel("P 2 entry 1")
i = 0
X2_values = []
V2_values = []
while i < len(X_test["X 2"]):
    X2_values.append(X_test["X 2"].values[i][0][1])
    V2_values.append(V_test["V 2"].values[i][0][1])

    i += 1
plt.subplot(2,2,2)

plt.plot(X2_values, V2_values)
plt.xlabel("X 2 entry 2")
plt.ylabel("P 2 entry 2")


i = 0
X3_values = []
V3_values = []
while i < len(X_test["X 2"]):
    X3_values.append(X_test["X 2"].values[i][1][0])
    V3_values.append(V_test["V 2"].values[i][1][0])

    i += 1
plt.subplot(2,2,3)
plt.plot(X3_values, V3_values)
plt.xlabel("X 2 entry 3")
plt.ylabel("P 2 entry 3")


i = 0
X4_values = []
V4_values = []
while i < len(X_test["X 2"]):
    X4_values.append(X_test["X 2"].values[i][1][1])
    V4_values.append(V_test["V 2"].values[i][1][1])

    i += 1
plt.subplot(2,2,4)
plt.plot(X4_values, V4_values)
plt.xlabel("X 2 entry 4")
plt.ylabel("P 2 entry 4")



In [ ]:
delta_t = 10**-4
record_steps = 100
simulation_repetitions = 200000
times = np.arange(delta_t*record_steps, simulation_repetitions*delta_t + delta_t*record_steps, delta_t*record_steps)


In [ ]:
plt.figure(figsize = (15,10))

i = 0

X1_values = []
V1_values = []
while i < len(X_test["X 1"]):
    X1_values.append(X_test["X 1"].values[i][0][0])
    V1_values.append(V_test["V 1"].values[i][0][0])

    i += 1
plt.subplot(2,2,1)
plt.plot(times, X1_values)
plt.ylabel("X 1 entry 1")
plt.xlabel("times")
i = 0
X2_values = []
V2_values = []
while i < len(X_test["X 1"]):
    X2_values.append(X_test["X 1"].values[i][0][1])
    V2_values.append(V_test["V 1"].values[i][0][1])

    i += 1
plt.subplot(2,2,2)

plt.plot(times, X2_values)
plt.ylabel("X 1 entry 2")
plt.xlabel("times")


i = 0
X3_values = []
V3_values = []
while i < len(X_test["X 1"]):
    X3_values.append(X_test["X 1"].values[i][1][0])
    V3_values.append(V_test["V 1"].values[i][1][0])

    i += 1
plt.subplot(2,2,3)
plt.plot(times, X3_values)
plt.ylabel("X 1 entry 3")
plt.xlabel("times")


i = 0
X4_values = []
V4_values = []
while i < len(X_test["X 1"]):
    X4_values.append(X_test["X 1"].values[i][1][1])
    V4_values.append(V_test["V 1"].values[i][1][1])

    i += 1
plt.subplot(2,2,4)
plt.plot(times, X4_values)
plt.ylabel("X 1 entry 4")
plt.xlabel("times")




# L2 norm


In [16]:
i = 0
X1_norms = []
while i < len(X_test["X 1"]):
    X1_norms.append(norm(V_test["V 2"][i]))
    i += 1

In [17]:
plt.plot(times, X1_norms)
plt.yscale("log")

NameError: name 'times' is not defined

# Lyapunov exponent

**Using the l_2 for the separation.**

In [106]:
# Load in each line in the text file
X_list3 = pd.read_csv(path + "X_simulation_1.txt",
                        names = ["X1"],
                      index_col=False)

# Split each line into a list in a list
data = []
for line in X_list3["X1"]:
    items = line.rstrip('\n').split(" ")
    data.append(items)
i = 0
while i < len(data):
    
    data[i] = list(filter(None, data[i]))
    i += 1

# Turn each element into a float
data_array = np.array(data, dtype=np.float32)    
    
# Turn every 3 lists into a single matrix by enclosing them in another list inside the array.
X_values = data_array.reshape(-1, 3, data_array.shape[1])

# X_values is a list of all X matrices recorded, it has the initial matrices of X1-X9 and then the 2nd recordings of X1-X9 etc.
# We need to break up every ninth element of X_values into new arrays as follows

X_matrices = [None] * 9  # List to store the nine new arrays

for i in range(9):
    X_matrices[i] = X_values[i::9] # i::9 starts at the ith element and goes up in steps of 9 until the we get out of index of the array.

# X_matrices is now a list of 9 arrays, each holding the time evolutions of X1-X9 respectively.

# Put each array into a column of a dataframe
labels = ["X1", "X2", "X3", "X4", "X5", "X6", "X7", "X8", "X9"]

delta_t = 10**-4
record_steps = 100
simulation_repetitions = 100000

times = np.arange(0, simulation_repetitions*delta_t + delta_t*record_steps, delta_t*record_steps)

X_DF = pd.DataFrame({"X1" : X_matrices[0].tolist(), "X2" : X_matrices[1].tolist(), "X3" : X_matrices[2].tolist(), "X4" : X_matrices[3].tolist(), "X5" : X_matrices[4].tolist(),
                     "X6" : X_matrices[5].tolist(), "X7" : X_matrices[6].tolist(), "X8" : X_matrices[7].tolist(), "X9" : X_matrices[8].tolist()}, index = times,
                    columns = labels)


In [109]:
# Load in each line in the text file
V_list3 = pd.read_csv(path + "V_simulation_1.txt",
                        names = ["V1"],
                      index_col=False)

# Split each line into a list in a list
data = []
for line in V_list3["V1"]:
    items = line.rstrip('\n').split(" ")
    data.append(items)
i = 0
while i < len(data):
    
    data[i] = list(filter(None, data[i]))
    i += 1

# Turn each element into a float
data_array = np.array(data, dtype=np.float32)    
    
# Turn every 3 lists into a single matrix by enclosing them in another list inside the array.
V_values = data_array.reshape(-1, 3, data_array.shape[1])

# V_values is a list of all V matrices recorded, it has the initial matrices of V1-V9 and then the 2nd recordings of V1-V9 etc.
# We need to break up every ninth element of V_values into new arrays as follows

V_matrices = [None] * 9  # List to store the nine new arrays

for i in range(9):
    V_matrices[i] = V_values[i::9] # i::9 starts at the ith element and goes up in steps of 9 until the we get out of index of the array.

# X_matrices is now a list of 9 arrays, each holding the time evolutions of X1-X9 respectively.
#print(V_matrices)
# Put each array into a column of a dataframe
labels = ["V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9"]

delta_t = 10**-4
record_steps = 100
simulation_repetitions = 100000

times = np.arange(0, simulation_repetitions*delta_t + delta_t*record_steps, delta_t*record_steps)

V_DF = pd.DataFrame({"V1" : V_matrices[0].tolist(), "V2" : V_matrices[1].tolist(), "V3" : V_matrices[2].tolist(), "V4" : V_matrices[3].tolist(), "V5" : V_matrices[4].tolist(),
                     "V6" : V_matrices[5].tolist(), "V7" : V_matrices[6].tolist(), "V8" : V_matrices[7].tolist(), "V9" : V_matrices[8].tolist()}, index = times,
                    columns = labels)


In [ ]:
A_list3 = pd.read_csv(path + "A_vector_initial.txt", sep = ";",
                        names = ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9"],
                      index_col=False)

In [30]:
X_list3 = pd.read_csv(path + "X_vector_initial.txt", sep = "\s+;,",
                      names = ["X1", "X2", "X3", "X4", "X5", "X6", "X7", "X8", "X9"],
                      index_col=False)
X_list3["X1"][0]

<ipython-input-30-9f5b6aa4e332>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  X_list3 = pd.read_csv(path + "X_vector_initial.txt", sep = "\s+;,",


'0.414088665335914,0.225567949423011,0.413464231323263,-2.539330153266858,-0.218056106847159,0.545812377560037,;0.413464231323263,2.539330153266858,1.469293298084035,0.145926865506495,-0.432501293641333,-0.077222086347351,;-0.218056106847159,-0.545812377560037,-0.432501293641333,0.077222086347351,-1.883381963419949,-0.371494814929506,;'