In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas import DataFrame as DF
from sympy import diff
from sympy.abc import x,y
from sympy import cos
from sympy import *
from sympy import lambdify
from itertools import product
import random
from scipy.linalg import norm

**Define path.**

In [2]:
# Defining path to folder raw data is saved in
path = "C:/Users/robtk/OneDrive/Desktop/DIAS Internship/Raw data/Harmonic oscillator warm up/"

### Set display of pandas dataframes and Series to 11 decimal places

In [3]:
pd.set_option("display.precision", 11)

**Read in the outputs for 2 2x2 matrices**

In [4]:
X2_by_2 = pd.read_pickle(path+"X.pkl")
V2_by_2 = pd.read_pickle(path+"V.pkl")

X2 = pd.read_pickle(path+"Xb.pkl")
V2 = pd.read_pickle(path+"Vb.pkl")

X_test = pd.read_pickle(path+"X_test.pkl")
V_test = pd.read_pickle(path+"V_test.pkl")

X_test = pd.read_pickle(path+"X_test9.pkl")
V_test = pd.read_pickle(path+"V_test9.pkl")


**Check that the Gauss' law constraint is conserved.**

In [6]:
# Define the commutator
def commutator(A,B):
    
    # matmul() multiplies two matrices together
    return np.matmul(A,B) - np.matmul(B,A)

## Are Xi still traceless

## Gauss' Law test

In [16]:
i = 0
while i < len(X_DF.iloc[:,0]):
    
    # Computes the sum of the commutators of Xi and Vi and if they equal zero move on to the next one.
    
    Gauss = (commutator(np.array(X_DF.iloc[i,0]), np.array(V_DF.iloc[i,0])) + 
             commutator(np.array(X_DF.iloc[i,1]), np.array(V_DF.iloc[i,1])) +
             commutator(np.array(X_DF.iloc[i,2]), np.array(V_DF.iloc[i,2])) + 
             commutator(np.array(X_DF.iloc[i,3]), np.array(V_DF.iloc[i,3])) +
             commutator(np.array(X_DF.iloc[i,4]), np.array(V_DF.iloc[i,4])) + 
             commutator(np.array(X_DF.iloc[i,5]), np.array(V_DF.iloc[i,5])) + 
             commutator(np.array(X_DF.iloc[i,6]), np.array(V_DF.iloc[i,6])) + 
             commutator(np.array(X_DF.iloc[i,7]), np.array(V_DF.iloc[i,7])) + 
             commutator(np.array(X_DF.iloc[i,8]), np.array(V_DF.iloc[i,8])) )

             
             
    i+=1
    print(i)
    # Check if the answer equals the zero matrix.
    if np.all(np.isclose(Gauss, 0)) != True:
        
    # If the sum is printed then the commutator does not equal the zero matrix stop the loop and print what the answer is.
        print(Gauss)
        
    print(Gauss)

1
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2
[[ 0.00000000e+00  3.02773964e-18 -8.57756261e-18]
 [-3.02773964e-18  0.00000000e+00  3.97745370e-18]
 [ 8.57756261e-18 -3.97745370e-18  0.00000000e+00]]
3
[[ 0.00000000e+00  1.14542538e-12 -1.05502877e-12]
 [-1.14542538e-12  0.00000000e+00  7.45027285e-13]
 [ 1.05502877e-12 -7.45027285e-13  0.00000000e+00]]
4
[[ 0.00000000e+00  1.02195410e-12 -1.36453241e-12]
 [-1.02195410e-12  0.00000000e+00  7.94796331e-13]
 [ 1.36453241e-12 -7.94796331e-13  0.00000000e+00]]
5
[[ 0.00000000e+00  3.53749336e-12  8.49412112e-13]
 [-3.53749336e-12  0.00000000e+00  4.77585482e-13]
 [-8.49412112e-13 -4.77585482e-13  0.00000000e+00]]
6
[[ 0.00000000e+00 -5.71818885e-13  3.13973507e-13]
 [ 5.71818885e-13  0.00000000e+00 -5.65492650e-12]
 [-3.13973507e-13  5.65492650e-12  0.00000000e+00]]
7
[[ 0.00000000e+00  1.03153605e-12 -2.16610737e-12]
 [-1.03153605e-12  0.00000000e+00 -1.23022468e-12]
 [ 2.16610737e-12  1.23022468e-12  0.00000000e+00]]
8
[[ 0.00000000e+00  1.30

**From the above code it is clear that Gauss' law is conserved throughout the simulation.**

**Now check if the Hamiltonian is conserved.**


In [38]:
# Define the Lagrangian

def L(X_list, V_list, g):
    
    term_1 = np.trace(np.array(V_list[0]) * np.array(V_list[0]) + np.array(V_list[1]) * np.array(V_list[1]) +
                      np.array(V_list[2]) * np.array(V_list[2]) + np.array(V_list[3]) * np.array(V_list[3]) +
                      np.array(V_list[4]) * np.array(V_list[4]) + np.array(V_list[5]) * np.array(V_list[5]) +
                      np.array(V_list[6]) * np.array(V_list[6]) + np.array(V_list[7]) * np.array(V_list[7]) +
                      np.array(V_list[8]) * np.array(V_list[8]))
    
    # Calculate the sum of commutators found in the second term of the lagrangian
    Sum2 = 0
    for matrix in X_list:
        el = np.array(matrix)
        Sum2 += np.trace( (commutator(el,np.array(X_list[0])))**2 + (commutator(el,np.array(X_list[1])))**2 + 
                          (commutator(el,np.array(X_list[2])))**2 + (commutator(el,np.array(X_list[3])))**2 + 
                          (commutator(el,np.array(X_list[4])))**2 + (commutator(el,np.array(X_list[5])))**2 + 
                          (commutator(el,np.array(X_list[6])))**2 + (commutator(el,np.array(X_list[7])))**2 + 
                          (commutator(el,np.array(X_list[8])))**2)  
    
    term_2 = 1/2 * Sum2
    
    return 1/(2*g**2) * (term_1 + term_2)

# Define the Hamiltonian

def H(X_list, V_list, g):
    
    
    term_1 = np.trace(np.array(V_list[0]) * np.array(V_list[0]) + np.array(V_list[1]) * np.array(V_list[1]) +
                      np.array(V_list[2]) * np.array(V_list[2]) + np.array(V_list[3]) * np.array(V_list[3]) +
                      np.array(V_list[4]) * np.array(V_list[4]) + np.array(V_list[5]) * np.array(V_list[5]) +
                      np.array(V_list[6]) * np.array(V_list[6]) + np.array(V_list[7]) * np.array(V_list[7]) +
                      np.array(V_list[8]) * np.array(V_list[8]))
    
    # Calculate the sum of commutators found in the second term of the lagrangian
    Sum2 = 0
    for matrix in X_list:
        el = np.array(matrix)
        print((commutator(el,np.array(X_list[0])))**2)
        Sum2 += np.trace( (commutator(el,np.array(X_list[0])))**2 + (commutator(el,np.array(X_list[1])))**2 + 
                          (commutator(el,np.array(X_list[2])))**2 + (commutator(el,np.array(X_list[3])))**2 + 
                          (commutator(el,np.array(X_list[4])))**2 + (commutator(el,np.array(X_list[5])))**2 + 
                          (commutator(el,np.array(X_list[6])))**2 + (commutator(el,np.array(X_list[7])))**2 + 
                          (commutator(el,np.array(X_list[8])))**2)  
        print(Sum2)
    term_2 = 1/2 * Sum2
    
    return 1/(2*g**2) * (term_1 - term_2)
    

In [ ]:
def H(X_list, V_list, g):
    T = 1.0/(2.0*g**2) * np.trace((np.array(V_list[0]) * np.array(V_list[0]) + np.array(V_list[1]) * np.array(V_list[1]) +
                      np.array(V_list[2]) * np.array(V_list[2]) + np.array(V_list[3]) * np.array(V_list[3]) +
                      np.array(V_list[4]) * np.array(V_list[4]) + np.array(V_list[5]) * np.array(V_list[5]) +
                      np.array(V_list[6]) * np.array(V_list[6]) + np.array(V_list[7]) * np.array(V_list[7]) +
                      np.array(V_list[8]) * np.array(V_list[8])))

    X[9] = {X1,X2,X3,X4,X5,X6,X7,X8,X9}; 

    matrix commutator_sum;  
    for (int i = 0; i < 9; i++)
    {
        for (int j = 0; j < 9; j++)
        {
            if(i == j)
                continue;
            commutator_sum += commutator(X[i],X[j])*commutator(X[i],X[j]); //can likely be more efficient by less function calls
        }
    }
    R_or_C U = - 1.0/(4.0*pow(g,2)) * commutator_sum.trace();
    return std:: abs(T + U);

In [40]:
i = 0
while i < len(X_DF["X1"].values):
    
    # Create a list of the 9 coordinate matrices for the position.
    X_list = [X_DF["X1"].values[i], X_DF["X2"].values[i], X_DF["X3"].values[i], X_DF["X4"].values[i], 
              X_DF["X5"].values[i], X_DF["X6"].values[i], X_DF["X7"].values[i], X_DF["X8"].values[i],
              X_DF["X9"].values[i]]
    print(X_list)
    V_list = [V_DF["V1"].values[i], V_DF["V2"].values[i], V_DF["V3"].values[i], V_DF["V4"].values[i], 
              V_DF["V5"].values[i], V_DF["V6"].values[i], V_DF["V7"].values[i], V_DF["V8"].values[i],
             V_DF["V9"].values[i]]
    #zero = [[0,0,0],[0,0,0],[0,0,0]]
    #V_list = [zero,zero, zero, zero, zero, zero, zero, zero, zero]

    
    print(H(X_list, V_list, 1))
    i += 1

[[[0.004140886478126049, 0.0022556795738637447, 0.025393301621079445], [0.0022556795738637447, 0.0041346424259245396, 0.014692933298647404], [0.025393301621079445, 0.014692933298647404, -0.008275529369711876]], [[-0.0021805609576404095, -0.005458123981952667, 0.0007722208392806351], [-0.005458123981952667, -0.004325013142079115, -0.006669480819255114], [0.0007722208392806351, -0.006669480819255114, 0.006505574099719524]], [[-0.009643184952437878, -0.017827453091740608, 0.007020303048193455], [-0.017827453091740608, 0.0026108594611287117, -0.0014798446791246533], [0.007020303048193455, -0.0014798446791246533, 0.007032325025647879]], [[0.01002652756869793, -0.009305058047175407, 0.018254278227686882], [-0.009305058047175407, -0.004242887254804373, 0.00442498130723834], [0.018254278227686882, 0.00442498130723834, -0.005783639848232269]], [[0.006084998603910208, 0.0034327618777751923, -0.011932255700230598], [0.0034327618777751923, 0.01249998901039362, -0.006568921729922295], [-0.011932255

**From derivation in page**

# Check conservation of angular momentum

**Angular momentum is $Tr(Xi\dot Xj - Xj\dot Xi)$**

In [ ]:
def angular_momentum(X2_by_2, V2_by_2):
    
    i = 0
    while i < len(X_DF["X1"].values):
        # Create a list of the 9 coordinate matrices for the position.
        X_list = [X_DF["X1"].values[i], X_DF["X2"].values[i], X_DF["X3"].values[i], X_DF["X4"].values[i], 
                  X_DF["X5"].values[i], X_DF["X6"].values[i], X_DF["X7"].values[i], X_DF["X8"].values[i],
                  X_DF["X9"].values[i]]
        V_list = [V_DF["V1"].values[i], V_DF["V2"].values[i], V_DF["V3"].values[i], V_DF["V4"].values[i], 
                  V_DF["V5"].values[i], V_DF["V6"].values[i], V_DF["V7"].values[i], V_DF["V8"].values[i],
                  V_DF["V9"].values[i]]  
        i += 1
        
    i = 0
    while i < len(X_list):
        
        j = 0
        Sum = 0
        while j < len(X_list):
            Sum += np.trace( np.matmul(X_list[i], V_list[j]) - np.matmul(V_list[j], X_list[i]) )
            j += 1
        print(Sum)
        
        i += 1

In [ ]:
angular_momentum(X2_by_2, V2_by_2)

In [ ]:
X_test["X 1"][0]

In [ ]:
plt.figure(figsize = (15,10))

i = 0

X1_values = []
V1_values = []
while i < len(X_test["X 1"]):
    X1_values.append(X_test["X 1"].values[i][0][0])
    V1_values.append(V_test["V 1"].values[i][0][0])

    i += 1
plt.subplot(2,2,1)
plt.plot(X1_values, V1_values)
plt.xlabel("X 1 entry 1")
plt.ylabel("P 1 entry 1")
i = 0
X2_values = []
V2_values = []
while i < len(X_test["X 1"]):
    X2_values.append(X_test["X 1"].values[i][0][1])
    V2_values.append(V_test["V 1"].values[i][0][1])

    i += 1
plt.subplot(2,2,2)

plt.plot(X2_values, V2_values)
plt.xlabel("X 1 entry 2")
plt.ylabel("P 1 entry 2")


i = 0
X3_values = []
V3_values = []
while i < len(X_test["X 1"]):
    X3_values.append(X_test["X 1"].values[i][1][0])
    V3_values.append(V_test["V 1"].values[i][1][0])

    i += 1
plt.subplot(2,2,3)
plt.plot(X3_values, V3_values)
plt.xlabel("X 1 entry 3")
plt.ylabel("P 1 entry 3")


i = 0
X4_values = []
V4_values = []
while i < len(X_test["X 1"]):
    X4_values.append(X_test["X 1"].values[i][1][1])
    V4_values.append(V_test["V 1"].values[i][1][1])

    i += 1
plt.subplot(2,2,4)
plt.plot(X4_values, V4_values)
plt.xlabel("X 1 entry 4")
plt.ylabel("P 1 entry 4")







In [ ]:
plt.figure(figsize = (15,10))

i = 0

X1_values = []
V1_values = []
while i < len(X_test["X 2"]):
    X1_values.append(X_test["X 2"].values[i][0][0])
    V1_values.append(V_test["V 2"].values[i][0][0])

    i += 1
plt.subplot(2,2,1)
plt.plot(X1_values, V1_values)
plt.xlabel("X 2 entry 1")
plt.ylabel("P 2 entry 1")
i = 0
X2_values = []
V2_values = []
while i < len(X_test["X 2"]):
    X2_values.append(X_test["X 2"].values[i][0][1])
    V2_values.append(V_test["V 2"].values[i][0][1])

    i += 1
plt.subplot(2,2,2)

plt.plot(X2_values, V2_values)
plt.xlabel("X 2 entry 2")
plt.ylabel("P 2 entry 2")


i = 0
X3_values = []
V3_values = []
while i < len(X_test["X 2"]):
    X3_values.append(X_test["X 2"].values[i][1][0])
    V3_values.append(V_test["V 2"].values[i][1][0])

    i += 1
plt.subplot(2,2,3)
plt.plot(X3_values, V3_values)
plt.xlabel("X 2 entry 3")
plt.ylabel("P 2 entry 3")


i = 0
X4_values = []
V4_values = []
while i < len(X_test["X 2"]):
    X4_values.append(X_test["X 2"].values[i][1][1])
    V4_values.append(V_test["V 2"].values[i][1][1])

    i += 1
plt.subplot(2,2,4)
plt.plot(X4_values, V4_values)
plt.xlabel("X 2 entry 4")
plt.ylabel("P 2 entry 4")



In [ ]:
delta_t = 10**-4
record_steps = 100
simulation_repetitions = 200000
times = np.arange(delta_t*record_steps, simulation_repetitions*delta_t + delta_t*record_steps, delta_t*record_steps)


In [ ]:
plt.figure(figsize = (15,10))

i = 0

X1_values = []
V1_values = []
while i < len(X_test["X 1"]):
    X1_values.append(X_test["X 1"].values[i][0][0])
    V1_values.append(V_test["V 1"].values[i][0][0])

    i += 1
plt.subplot(2,2,1)
plt.plot(times, X1_values)
plt.ylabel("X 1 entry 1")
plt.xlabel("times")
i = 0
X2_values = []
V2_values = []
while i < len(X_test["X 1"]):
    X2_values.append(X_test["X 1"].values[i][0][1])
    V2_values.append(V_test["V 1"].values[i][0][1])

    i += 1
plt.subplot(2,2,2)

plt.plot(times, X2_values)
plt.ylabel("X 1 entry 2")
plt.xlabel("times")


i = 0
X3_values = []
V3_values = []
while i < len(X_test["X 1"]):
    X3_values.append(X_test["X 1"].values[i][1][0])
    V3_values.append(V_test["V 1"].values[i][1][0])

    i += 1
plt.subplot(2,2,3)
plt.plot(times, X3_values)
plt.ylabel("X 1 entry 3")
plt.xlabel("times")


i = 0
X4_values = []
V4_values = []
while i < len(X_test["X 1"]):
    X4_values.append(X_test["X 1"].values[i][1][1])
    V4_values.append(V_test["V 1"].values[i][1][1])

    i += 1
plt.subplot(2,2,4)
plt.plot(times, X4_values)
plt.ylabel("X 1 entry 4")
plt.xlabel("times")




# L2 norm


In [ ]:
i = 0
X1_norms = []
while i < len(X_test["X 1"]):
    X1_norms.append(norm(V_test["V 2"][i]))
    i += 1

In [ ]:
plt.plot(times, X1_norms)
plt.yscale("log")

# Lyapunov exponent

**Using the l_2 for the separation.**

In [43]:
# Load in each line in the text file
X_list3 = pd.read_csv(path + "X_vector_test4.txt",
                        names = ["X1"],
                      index_col=False)

# Split each line into a list in a list
data = []
for line in X_list3["X1"]:
    items = line.rstrip('\n').split(" ")
    data.append(items)
i = 0
while i < len(data):
    
    data[i] = list(filter(None, data[i]))
    i += 1

# Turn each element into a float
data_array = np.array(data, dtype=np.float32)    
    
# Turn every 3 lists into a single matrix by enclosing them in another list inside the array.
X_values = data_array.reshape(-1, 3, data_array.shape[1])

# X_values is a list of all X matrices recorded, it has the initial matrices of X1-X9 and then the 2nd recordings of X1-X9 etc.
# We need to break up every ninth element of X_values into new arrays as follows

X_matrices = [None] * 9  # List to store the nine new arrays

for i in range(9):
    X_matrices[i] = X_values[i::9] # i::9 starts at the ith element and goes up in steps of 9 until the we get out of index of the array.

# X_matrices is now a list of 9 arrays, each holding the time evolutions of X1-X9 respectively.

# Put each array into a column of a dataframe
labels = ["X1", "X2", "X3", "X4", "X5", "X6", "X7", "X8", "X9"]

delta_t = 10**-4
record_steps = 500000
simulation_repetitions = 10000000

times = np.arange(0, simulation_repetitions*delta_t + delta_t*record_steps, delta_t*record_steps)

X_DF = pd.DataFrame({"X1" : X_matrices[0].tolist(), "X2" : X_matrices[1].tolist(), "X3" : X_matrices[2].tolist(), "X4" : X_matrices[3].tolist(), "X5" : X_matrices[4].tolist(),
                     "X6" : X_matrices[5].tolist(), "X7" : X_matrices[6].tolist(), "X8" : X_matrices[7].tolist(), "X9" : X_matrices[8].tolist()}, index = times,
                    columns = labels)


In [53]:
[None] * 9

[None, None, None, None, None, None, None, None, None]

In [51]:
i = 0
print(X_values[i::9])
print("hi")

[[[ 0.00414089  0.00225568  0.0253933 ]
  [ 0.00225568  0.00413464  0.01469293]
  [ 0.0253933   0.01469293 -0.00827553]]

 [[ 0.00414089  0.00225568  0.0253933 ]
  [ 0.00225568  0.00413464  0.01469293]
  [ 0.0253933   0.01469293 -0.00827553]]

 [[-0.02013068 -0.01008535 -0.01026718]
  [-0.01008535  0.00815124 -0.0017246 ]
  [-0.01026718 -0.0017246   0.01197944]]

 [[ 0.00187169  0.0090008  -0.0113841 ]
  [ 0.0090008  -0.01152523 -0.00760265]
  [-0.0113841  -0.00760265  0.00965354]]

 [[ 0.01219768  0.02260769  0.00672732]
  [ 0.02260769 -0.00453818  0.01027653]
  [ 0.00672732  0.01027653 -0.0076595 ]]

 [[ 0.00616962  0.0067392   0.00953917]
  [ 0.0067392   0.01244184  0.00766069]
  [ 0.00953917  0.00766069 -0.01861146]]

 [[-0.00303891 -0.0113787  -0.01054169]
  [-0.0113787   0.00533804 -0.00144871]
  [-0.01054169 -0.00144871 -0.00229913]]

 [[-0.00456667 -0.00418796  0.00344281]
  [-0.00418796  0.00031545 -0.01271986]
  [ 0.00344281 -0.01271986  0.00425121]]

 [[ 0.02907653  0.014661

In [12]:
# Load in each line in the text file
V_list3 = pd.read_csv(path + "V_vector_test4.txt",
                        names = ["V1"],
                      index_col=False)

# Split each line into a list in a list
data = []
for line in V_list3["V1"]:
    items = line.rstrip('\n').split(" ")
    data.append(items)
i = 0
while i < len(data):
    
    data[i] = list(filter(None, data[i]))
    i += 1

# Turn each element into a float
data_array = np.array(data, dtype=np.float32)    
    
# Turn every 3 lists into a single matrix by enclosing them in another list inside the array.
V_values = data_array.reshape(-1, 3, data_array.shape[1])

# V_values is a list of all V matrices recorded, it has the initial matrices of V1-V9 and then the 2nd recordings of V1-V9 etc.
# We need to break up every ninth element of V_values into new arrays as follows

V_matrices = [None] * 9  # List to store the nine new arrays

for i in range(9):
    V_matrices[i] = V_values[i::9] # i::9 starts at the ith element and goes up in steps of 9 until the we get out of index of the array.

# X_matrices is now a list of 9 arrays, each holding the time evolutions of X1-X9 respectively.
#print(V_matrices)
# Put each array into a column of a dataframe
labels = ["V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9"]

delta_t = 10**-4
record_steps = 500000
simulation_repetitions = 10000000

times = np.arange(0, simulation_repetitions*delta_t + delta_t*record_steps, delta_t*record_steps)

V_DF = pd.DataFrame({"V1" : V_matrices[0].tolist(), "V2" : V_matrices[1].tolist(), "V3" : V_matrices[2].tolist(), "V4" : V_matrices[3].tolist(), "V5" : V_matrices[4].tolist(),
                     "V6" : V_matrices[5].tolist(), "V7" : V_matrices[6].tolist(), "V8" : V_matrices[7].tolist(), "V9" : V_matrices[8].tolist()}, index = times,
                    columns = labels)


In [8]:
A_list3 = pd.read_csv(path + "A_vector_initial.txt", sep = ";",
                        names = ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9"],
                      index_col=False)

In [9]:
X_list3 = pd.read_csv(path + "X_vector_initial.txt", sep = "\s+;,",
                      names = ["X1", "X2", "X3", "X4", "X5", "X6", "X7", "X8", "X9"],
                      index_col=False)
X_list3["X1"][0]

<ipython-input-9-9f5b6aa4e332>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  X_list3 = pd.read_csv(path + "X_vector_initial.txt", sep = "\s+;,",


'0.004140886653359  0.002255679494230  0.025393301532669'