In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas import DataFrame as DF
from sympy import diff
from sympy.abc import x,y
from sympy import cos
from sympy import *
from sympy import lambdify
from itertools import product
import random
from scipy.linalg import norm

**Define path.**

In [3]:
# Defining path to folder raw data is saved in
path = "C:/Users/robtk/OneDrive/Desktop/DIAS Internship/Raw data/Harmonic oscillator warm up/"

### Set display of pandas dataframes and Series to 11 decimal places

In [5]:
pd.set_option("display.precision", 11)

**Read in the outputs for 2 2x2 matrices**

In [31]:
X2_by_2 = pd.read_pickle(path+"X.pkl")
V2_by_2 = pd.read_pickle(path+"V.pkl")

**Check that the Gauss' law constraint is conserved.**

In [35]:
X2_by_2

X 1  \
0                  [[-1.2648031177873595, 0.28965090823750295], [...   
0.1                [[-1.266024586128383, 0.3075498233453539], [0....   
0.2                [[-1.2672461453989399, 0.3254499316527957], [0...   
0.3                [[-1.2684206793138693, 0.3427458500505543], [0...   
0.4                [[-1.2695023596759814, 0.3588490235768357], [0...   
...                                                              ...   
9.5                [[-1.2553307128237747, 0.3864624075261496], [0...   
9.6                [[-1.256553976865044, 0.4045837340315353], [0....   
9.700000000000001  [[-1.2576228624582029, 0.4207220073740257], [0...   
9.8                [[-1.2584778821555025, 0.43411357363433767], [...   
9.9                [[-1.2590696112331297, 0.4441241603022393], [0...   

                                                                 X 2  
0                  [[-0.988786234734847, -8.808868141843881], [-9...  
0.1                [[-0.9924837407927861, -8.82448803046022], [-9...  
0.2                [[-0.9961812908590642, -8.840108058987312], [-...  
0.3                [[-0.9998774849649374, -8.855750406355776], [-...  
0.4                [[-1.0035714229022201, -8.871438686484098], [-...  
...                                                              ...  
9.5                [[-1.3513982692174915, -10.418536239755582], [...  
9.6                [[-1.3554268690283275, -10.435619594516812], [...  
9.700000000000001  [[-1.3594517279362057, -10.452779362294871], [...  
9.8                [[-1.3634722119282914, -10.47004855952829], [-...  
9.9                [[-1.3674881329031612, -10.487456115722527], [...  

[100 rows x 2 columns]

In [8]:
# Define the commutator
def commutator(A,B):
    
    # matmul() multiplies two matrices together
    return np.matmul(A,B) - np.matmul(B,A)

In [9]:
i = 0
while i < len(X2_by_2.iloc[:,0]):
    
    # Computes the sum of the commutators of Xi and Vi and if they equal zero move on to the next one.
    
    Gauss = commutator(np.array(X2_by_2.iloc[i,0]), np.array(V2_by_2.iloc[i,0])) + commutator(np.array(X2_by_2.iloc[i,1]), np.array(V2_by_2.iloc[i,1]))
    i+=1
    print(i)
    # Check if the answer equals the zero matrix.
    if np.all(np.isclose(Gauss, 0)) != True:
        
    # If the sum is printed then the commutator does not equal the zero matrix stop the loop and print what the answer is.
        print(Gauss)
        break
        
    print(Gauss)

1
[[ 7.77156117e-15  3.10862447e-14]
 [-1.79856130e-14 -7.99360578e-15]]
2
[[ 1.50990331e-14  2.84217094e-14]
 [-1.48769885e-14 -1.33226763e-14]]
3
[[ 1.82076576e-14  2.90878432e-14]
 [-1.62092562e-14 -1.82076576e-14]]
4
[[ 2.75335310e-14  2.99760217e-14]
 [-2.46469511e-14 -2.75335310e-14]]
5
[[ 4.06341627e-14  2.79776202e-14]
 [-2.50910404e-14 -4.05231404e-14]]
6
[[ 3.57491814e-14  2.97539771e-14]
 [-2.62012634e-14 -3.57491814e-14]]
7
[[ 3.69704267e-14  3.19744231e-14]
 [-2.93098879e-14 -3.87467836e-14]]
8
[[ 4.14113188e-14  3.48610030e-14]
 [-3.38618023e-14 -3.96349620e-14]]
9
[[ 4.60742555e-14  3.11972670e-14]
 [-3.22519789e-14 -4.78506124e-14]]
10
[[ 4.47211712e-14  2.91711100e-14]
 [-2.92058044e-14 -4.47211712e-14]]
11
[[ 4.82391904e-14  2.96707103e-14]
 [-2.93653990e-14 -4.64628336e-14]]
12
[[ 5.42899059e-14  2.62012634e-14]
 [-2.98649994e-14 -5.42899059e-14]]
13
[[ 5.06261699e-14  2.99760217e-14]
 [-3.24185123e-14 -5.05151476e-14]]
14
[[ 4.94049246e-14  2.70894418e-14]
 [-3.1086

**From the above code it is clear that Gauss' law is conserved throughout the simulation.**

**Now check if the Hamiltonian is conserved.**


In [10]:
# Define the Lagrangian

def L(X_list, V_list, g):
    
    X_array = np.array(X_list)
    V_array = np.array(X_list)
    term_1 =  np.sum( np.trace( (V_array)**2 ) )
    
    # Calculate the sum of commutators found in the second term of the lagrangian
    for el in X_list:
        X_cut = [x for x in X_list if x != el]
        Sum2 = np.sum( np.trace( (commutator(el,X_cut))**2 ) ) 
    
    term_2 = 1/2 * Sum2
    
    return 1/(2*g**2) * (term_1 + term_2)

# Define the Hamiltonian

def H(X_list, V_list, g):
    
    V_array = np.array(X_list)
    V_array_T = np.transpose(V_array)
    
    return sum( V_array_T * V_array /g**2) - L(X_list, V_list, g)
    

In [11]:
V2_by_2

V 1  \
0                  [[-0.12056495110501841, 1.7695576970987381], [...   
0.1                [[-0.12293121509432986, 1.7999734588103529], [...   
0.2                [[-0.12057689632601384, 1.7697211753819215], [...   
0.3                [[-0.11354807401713776, 1.679422038844256], [-...   
0.4                [[-0.102055953882069, 1.531815551414121], [-1....   
...                                                              ...   
9.5                [[-0.12785800805497968, 1.8831984301539302], [...   
9.6                [[-0.11565780787416945, 1.7264656199285744], [...   
9.700000000000001  [[-0.09710299873130834, 1.488142630955383], [-...   
9.8                [[-0.07305645688529439, 1.1793335003816856], [...   
9.9                [[-0.04466009360102731, 0.8147105614815209], [...   

                                                                 V 2  
0                  [[-0.3696892043800882, -1.5626698061744178], [...  
0.1                [[-0.3697800075050011, -1.5616465939032302], [...  
0.2                [[-0.3697061623936174, -1.5627376246795663], [...  
0.3                [[-0.3695174205987425, -1.5661352206002537], [...  
0.4                [[-0.36926287514974304, -1.571929358455459], [...  
...                                                              ...  
9.5                [[-0.403010805542756, -1.7056717217486954], [-...  
9.6                [[-0.40268803522367874, -1.7115904531502943], ...  
9.700000000000001  [[-0.4022732656525274, -1.720928724049069], [-...  
9.8                [[-0.4018206947481504, -1.7334066826741967], [...  
9.9                [[-0.40136467677955767, -1.7484886781514128], ...  

[100 rows x 2 columns]

In [12]:
i = 0
while i < len(X2_by_2["X 1"].values):
    
    # Create a list of the two coordinate matrices for the position.
    X_list = [X2_by_2["X 1"].values[i], X2_by_2["X 2"].values[i]]
    V_list = [V2_by_2["V 1"].values[i], V2_by_2["V 2"].values[i]]

    
    print(H(X_list, V_list, 1))
    i += 1

[[-48.25789996  27.73853105]
 [-36.2237991  -27.49335605]]
[[-48.4326014   27.83616935]
 [-36.38070646 -27.61657282]]
[[-48.66420155  27.87739615]
 [-36.5938282  -27.79657475]]
[[-48.94846988  27.86695436]
 [-36.8586346  -28.02920897]]
[[-49.27376407  27.81702406]
 [-37.16327539 -28.30290753]]
[[-49.62244211  27.745786  ]
 [-37.4899874  -28.60009785]]
[[-49.97315147  27.6751046 ]
 [-37.8173693  -28.89949057]]
[[-50.30369552  27.62763225]
 [-38.12322718 -29.17894545]]
[[-50.59408799  27.62372691]
 [-38.38760503 -29.4185253 ]]
[[-50.82936838  27.6786124 ]
 [-38.59557771 -29.60331091]]
[[-51.00177373  27.80018853]
 [-38.73940552 -29.72557207]]
[[-51.11194287  27.98781669]
 [-38.81972954 -29.78597063]]
[[-51.16895859  28.23227651]
 [-38.84561489 -29.79360105]]
[[-51.18919466  28.51692697]
 [-38.83340872 -29.76483532]]
[[-51.19410545  28.81993324]
 [-38.80454918 -29.7211105 ]]
[[-51.20725297  29.11726301]
 [-38.78261678 -29.68595356]]
[[-51.25098436  29.38603686]
 [-38.79003722 -29.68165754

**From derivation in page**

# Check conservation of angular momentum

**Angular momentum is $Tr(Xi\dot Xj - Xj\dot Xi)$**

In [13]:
def angular_momentum(X2_by_2, V2_by_2):
    
    i = 0
    while i < len(X2_by_2):
        
        Xi = X2_by_2[i]
        Vi = V2_by_2[i]
        np.sum(np.trace( np.matmul(Xi, V2_by_2) - np.matmul(X2_by_2, Vi) ))
        
        i += 1

In [14]:
angular_momentum(X2_by_2, V2_by_2)

KeyError: 0

# Lyapunov exponent

**Using the l_2 for the separation.**

In [21]:
A_list3 = pd.read_csv(path + "A_vector_initial.txt", sep = "\s+|;|,",
                      names = ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9"],
                      index_col=False)
A_list3["A1"]

<ipython-input-21-8527f7864e58>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  A_list3 = pd.read_csv(path + "A_vector_initial.txt", sep = "\s+|;|,",


0   -9.000000e-15
1   -9.000000e-15
2   -9.000000e-15
3   -9.000000e-15
4   -9.000000e-15
5   -9.000000e-15
6   -9.000000e-15
7   -9.000000e-15
8   -9.000000e-15
Name: A1, dtype: float64

In [30]:
X_list3 = pd.read_csv(path + "X_vector_initial.txt", sep = "\s+;,",
                      names = ["X1", "X2", "X3", "X4", "X5", "X6", "X7", "X8", "X9"],
                      index_col=False)
X_list3["X1"][0]

<ipython-input-30-9f5b6aa4e332>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  X_list3 = pd.read_csv(path + "X_vector_initial.txt", sep = "\s+;,",


'0.414088665335914,0.225567949423011,0.413464231323263,-2.539330153266858,-0.218056106847159,0.545812377560037,;0.413464231323263,2.539330153266858,1.469293298084035,0.145926865506495,-0.432501293641333,-0.077222086347351,;-0.218056106847159,-0.545812377560037,-0.432501293641333,0.077222086347351,-1.883381963419949,-0.371494814929506,;'